tomasnorre/crawler

.scrutinizer.yml
.travis.yml

Change-Id: I0bdb6fc5c310136b837f9ccfae85e724c7390e56
Fixes #9

[TASK] Setting  up TravisCI and Scrutinizer

---

.travis.yml

[BUG] Add code-coverage upload to travis

---

domain/process/class.tx_crawler_domain_process_manager.php
ext_conf_template.txt

Makes it possible to set if you want multiCrawler process
to verbose output or not.
Resolves #15

[FEATURE] MultiCrawler Output

---

class.tx_crawler_contextMenu.php

[BUG] Fix ClickMenu bug for 7.6

---

view/process/class.tx_crawler_view_process_list.php

[TASK] Fix button in backend for TYPO3 7 LTS.

---

class.tx_crawler_lib.php
ext_autoload.php
ext_localconf.php
ext_tables.sql
hooks/class.tx_crawler_hooks_processCleanUp.php

Please don't merge before review done.

[TASK] Manage dispatched php processes

---

Configuration/TCA/tx_crawler_configuration.php
class.tx_crawler_api.php
class.tx_crawler_lib.php
cli/class.tx_crawler_cli.php
cli/class.tx_crawler_cli_flush.php
cli/class.tx_crawler_cli_im.php
ext_tables.php
modfunc1/class.tx_crawler_modfunc1.php

[TASK] Remove version comparisons for TYPO3 4.x

---

class.tx_crawler_api.php

[TASK] Remove commented require statements

---

modfunc1/class.tx_crawler_modfunc1.php

[BUG] Refresh icon not displayed in TYPO3 7 LTS

---

hooks/class.tx_crawler_hooks_processCleanUp.php

Updated after scrutinizer feedback

[FIX] Ensure traversable else return

---

class.tx_crawler_lib.php
scheduler/class.tx_crawler_scheduler_crawl.php
scheduler/class.tx_crawler_scheduler_crawlAdditionalFieldProvider.php
scheduler/class.tx_crawler_scheduler_crawlMultiProcess.php
scheduler/class.tx_crawler_scheduler_crawlMultiProcessAdditionalFieldProvider.php
scheduler/class.tx_crawler_scheduler_flush.php
scheduler/class.tx_crawler_scheduler_flushAdditionalFieldProvider.php
scheduler/class.tx_crawler_scheduler_im.php
scheduler/class.tx_crawler_scheduler_imAdditionalFieldProvider.php

Replacing all occurrences of namespaced classes with their Tx_ counterparts
Resolves #26

[BUGFIX] Restore TYPO3 4.5 compatibility

---

class.tx_crawler_lib.php

[TASK] Remove deprecated call of GeneralUtility::loadTCA()

---

.travis.yml
Tests/Functional/class.tx_crawler_api_testcase.php
Tests/Functional/data/canCreateQueueEntrysUsingConfigurationRecord.xml
ext_emconf.php

[TASK] Add Travis Config for both TYPO3 6 and 7LTS

---

Documentation/ExtCrawler/Configuration/ConfigurationRecords/Index.rst
Documentation/ExtCrawler/Configuration/PageTsconfigReference(txCrawlercrawlercfg)/Index.rst
Documentation/ExtCrawler/Index.rst
Documentation/ExtCrawler/Targets.rst

* Add description for configuration record form fields
* Add links for cross referencing
* Add note about _ADDTABLE option
* Cleanup quotes
* Change key name in code example to make it more verbose

Improve configuration record documentation

---

Tests/Functional/class.tx_crawler_api_testcase.php
Tests/Functional/data/pages.xml
Tests/Functional/data/sys_template.xml
Tests/Functional/data/typoscript_setup.txt
Tests/Unit/class.tx_crawler_lib_testcase.php
class.tx_crawler_lib.php
ext_conf_template.txt

[TASK] config.absRefPrefix not respected by tx_crawler_lib::getFronendBasePath()

---

Configuration/TCA/tx_crawler_configuration.php

[TASK] Re-enable Workspace after Core Issue #70052 fixed

---

ext_tables.php

in ExtensionManagementUtility::insertModuleFunction call
Resolves: #74

[TASK] Replace deprecated parameter

---

Configuration/TCA/tx_crawler_configuration.php

[TASK] Missing "hide"/"disable" field in the configuration record form

---

Configuration/TCA/tx_crawler_configuration.php

This reverts commit 9d9fe409a856f7559d1c943bd98c3b8e57832f28.
See: https://github.com/AOEpeople/crawler/issues/82

Revert "[TASK] Re-enable Workspace after Core Issue #70052 fixed"

---

Configuration/TCA/tx_crawler_configuration.php

Fixes https://github.com/AOEpeople/crawler/issues/84

[BUGFIX] Fix broken displayCond

---

template/process/list.php

[TASK] Remove "Add Process"-button when no more queue-item can be assigned

---

Configuration/TCA/tx_crawler_configuration.php
Documentation/ExtCrawler/Introduction/WhatsNew/Index.rst
Tests/Functional/class.tx_crawler_api_testcase.php
class.tx_crawler_lib.php
domain/events/class.tx_crawler_domain_events_dispatcher.php
ext_tables.sql
locallang_db.xml

[BUGFIX] Remove dependency for workspaces

---

class.tx_crawler_lib.php

[TASK] Update exception for "no typoscript template found"

---

composer.json
ext_emconf.php

[FEATURE] Adjust autoload configuration for TYPO3 7+

---

Classes/Tasks/ProcessCleanupTask.php
ext_localconf.php
locallang_db.xml

[TASK] Add scheduler task for process cleanup hook

---

Classes/Utility/SignalSlotUtility.php
class.tx_crawler_lib.php

[FEATURE] Emit signals before/after a queue item is processed

---

class.tx_crawler_lib.php

[BUGFIX] Switch to PHP 5.3 compatible array syntax

---

Classes/Utility/TypoScriptUtility.php
Tests/Functional/Fixtures/pages.xml
Tests/Functional/Fixtures/sys_template.xml
Tests/Functional/Fixtures/typoscript_setup.txt
Tests/Functional/Utility/TypoScriptUtilityTest.php
Tests/Functional/class.tx_crawler_api_testcase.php
Tests/Functional/data/sys_template.xml
class.tx_crawler_lib.php

Solves issue #118 
The tests are running green locally, but as .travis.yml is not adjusted yet to run the namespaced Tests the Travis Build is not including the new test from here.
Would be cool if you could verify this locally @srotsch. 
From my tests it works as expected.
Update: For some reason the regular Functional tests failed, that i would have to look into. That didn't happen on the first commits.

[TASK] Auto detect TypoScript Template

---

Classes/Task/ProcessCleanupTask.php
Classes/Utility/SchedulerUtility.php
Classes/Utility/TypoScriptUtility.php
Tests/Functional/Fixtures/pages.xml
Tests/Functional/Utility/TypoScriptUtilityTest.php

[FEATURE] Adjust namespace of ProcessCleanupTask

---

Classes/Utility/BackendUtility.php

[BUGFIX] #1442236317: MenuItem "" is not valid (More information) (#148)

---

Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php

[BUGFIX] Scheduler Tasks broken after upgrade to 5.1.0 (#142)

---

Classes/Utility/HookUtility.php
class.tx_crawler_lib.php

[BUGFIX] It's not possible to "add process" after upgrade to 5.1.0 (#145)

---

.travis.yml
Tests/Functional/Domain/Model/ProcessTest.php
Tests/Unit/CrawlerLibTest.php
Tests/Unit/Domain/Model/ProcessCollectionTest.php
Tests/Unit/Domain/Model/ProcessManagerTest.php
Tests/Unit/Domain/Model/ProcessTest.php
Tests/Unit/Domain/Model/QueueTest.php
domain/process/class.tx_crawler_domain_process.php
domain/process/class.tx_crawler_domain_process_manager.php
domain/queue/class.tx_crawler_domain_queue_repository.php
domain/reason/class.tx_crawler_domain_reason.php
modfunc1/class.tx_crawler_modfunc1.php
view/class.tx_crawler_view_pagination.php
view/process/class.tx_crawler_view_process_list.php

[FEATURE] Write tests for the Domain Model (#141)

---

Classes/Task/CrawlerQueueTask.php
Tests/Unit/Hooks/CrawlMultiProcessTaskTest.php
Tests/Unit/Hooks/CrawlerQueueTaskTest.php
Tests/Unit/Hooks/CrawlerTaskTest.php
Tests/Unit/Hooks/FlushQueueTaskTest.php
Tests/Unit/Hooks/ProcessCleanupTaskTest.php

[FEATURE] Write tests for Hooks (#156)

---

domain/process/class.tx_crawler_domain_process_manager.php

It is currently not possible to start a cli crawler process in the backend when having a windows server.
I have found a pull request from the [old github mirror repo](https://github.com/TYPO3-extensions/crawler/pull/1), tested the changes and would now like to add them to the extension.

[BUGFIX] Starting a new cli process is not working with windows

---

class.tx_crawler_lib.php

We need the post process signal slot also for use with the crawler_im cli task.

[TASK] add post process signal slot also for use with crawler_im

---

.php_cs

[TASK] Add initial defaults for php-cs-fixer

---

Classes/Utility/IconUtility.php
Configuration/TCA/Overrides/tx_crawler_configuration.php
composer.json
ext_emconf.php
modfunc1/class.tx_crawler_modfunc1.php

[FEATURE] Drop support for TYPO3 6.2 (#224)

---

Classes/Task/CrawlerQueueTask.php
Classes/Task/CrawlerTask.php
Tests/Functional/class.tx_crawler_api_testcase.php
Tests/Unit/Domain/Model/EventDispatcherTest.php
class.tx_crawler_api.php
class.tx_crawler_lib.php
class.tx_crawler_tcaFunc.php
cli/class.tx_crawler_cli.php
cli/class.tx_crawler_cli_flush.php
cli/class.tx_crawler_cli_im.php
domain/events/class.tx_crawler_domain_events_dispatcher.php
domain/process/class.tx_crawler_domain_process.php
domain/process/class.tx_crawler_domain_process_collection.php
domain/process/class.tx_crawler_domain_process_repository.php
domain/queue/class.tx_crawler_domain_queue_entry.php
domain/queue/class.tx_crawler_domain_queue_repository.php
modfunc1/class.tx_crawler_modfunc1.php

[CLEANUP] Remove superfluous PHPDoc annotations

---

class.tx_crawler_lib.php
cli/class.tx_crawler_cli.php
cli/class.tx_crawler_cli_flush.php
cli/class.tx_crawler_cli_im.php
domain/process/class.tx_crawler_domain_process_collection.php
modfunc1/class.tx_crawler_modfunc1.php

[CLEANUP] Remove legacy TYPO3 CMS 4.x XCLASS registration

---

view/process/class.tx_crawler_view_process_list.php

[BUGFIX] Added removed getIconForState + needed functions (#244)

---

template/pagination.php

[BUGFIX] Changed Url-generation for pagination (#89)

---

Classes/Task/CrawlMultiProcessTaskAdditionalFieldProvider.php
Classes/Task/CrawlerQueueTaskAdditionalFieldProvider.php
Classes/Task/CrawlerTaskAdditionalFieldProvider.php
Classes/Task/FlushQueueTaskAdditionalFieldProvider.php

[CLEANUP] Changed PHPDoc for getAdditionalFields() (#254)

---

.scrutinizer.yml
.travis.yml

[TASK] Fix code-coverage reports whitelisting (#251)

---

Classes/Backend/BackendModule.php
Classes/Controller/CrawlerController.php
Classes/Service/ProcessService.php
Classes/Task/CrawlMultiProcessTask.php
Classes/Task/CrawlMultiProcessTaskAdditionalFieldProvider.php
Classes/Task/CrawlerQueueTaskAdditionalFieldProvider.php
Classes/Task/CrawlerTaskAdditionalFieldProvider.php
Classes/Task/FlushQueueTaskAdditionalFieldProvider.php

Resolved #174 
It's not all solved, but it's improved, would still like to discussion some of the suggestions still open with you @srotsch .

[CLEANUP] Added scrutinizer suggestions (#174)

---

Classes/Controller/CrawlerController.php
Tests/Unit/Controller/CrawlerControllerTest.php

[FEATURE] Configuration_hash for carwler_queue (#186)

---

Classes/Api/CrawlerApi.php
Classes/Backend/BackendModule.php
Classes/Hooks/ProcessCleanUpHook.php
Classes/Service/ProcessService.php
Tests/Functional/Api/CrawlerApiTest.php
Tests/Unit/Controller/CrawlerControllerTest.php
Tests/Unit/Domain/Model/ProcessServiceTest.php
cli/crawler_cli.php
cli/crawler_cli.phpsh
cli/crawler_flush.php
cli/crawler_im.php
cli/crawler_multiprocess.php

[CLEANUP] Adjust variable names to reflect renamed Classes (#250)

---

Classes/Backend/BackendModule.php

[TASK] Add Warn when no configuration is selected (#191)

---

Documentation/ExtCrawler/Configuration/PageTsconfigReference(txCrawlercrawlercfg)/Index.rst

[TASK] Correcting documentation (#265)

---

ext_conf_template.txt

[FEATURE] Splitting extension settings into tabs (#304)

---

ext_tables.sql

Resolves: #273 
@aschmutt @samowitsch Can you please test this ?
Thanks.

[TASK] Change NOT NULL for pidsonly field

---

Classes/Api/CrawlerApi.php
Classes/Controller/CrawlerController.php
Classes/Utility/SignalSlotUtility.php

[CLEANUP] Fix problems with PHP 7.2

---

Classes/Backend/BackendModule.php
Classes/ClickMenu/CrawlerClickMenu.php
Classes/Controller/CrawlerController.php
Classes/Utility/BackendUtility.php
ext_conf_template.txt

Please don't merge, but please review.

TYPO3 V8 fixes

---

Classes/Backend/BackendModule.php
Classes/Backend/View/ProcessListView.php
Classes/Controller/CrawlerController.php

This solves parts of issue #347 (it has some ugly hacks though).
In order to get a quickly running solution, I implemented the section functions from the `DocumentTemplate` class into the `BackendModule` class.
I'll probably work on this PR since I don't thing, that the fix for the missing configurations from the backend should be placed here and that they make much more sense in #346

Make module compatible with TYPO3 9

---

Classes/Controller/CrawlerController.php

[TASK] Use LoggerAPI instead of deprecated constant

---

ext_tables.sql

Fix error 'processing_instruction_filter has no default value'

---

Classes/Controller/CrawlerController.php

Working with the extension revealed two issues when working with the scheduler task regarding SQL errors due to errorneous queries.
This should be fixed by these changes.

[BUGFIX] Resolve SQL issues

---

Classes/Api/CrawlerApi.php
Classes/Backend/BackendModule.php
Classes/Domain/Repository/AbstractRepository.php
Classes/Service/ProcessService.php
Tests/Functional/Domain/Repository/ProcessRepositoryTest.php
Tests/Functional/Domain/Repository/QueueRepositoryTest.php
composer.json

After Refactoring the Domain/Model+Repository (#323, #328) we experience problems with the Mocking and functions calls.
This commit will fix this

[BUGFIX] Change incorrect mocking and function calls 

---

Classes/Backend/BackendModule.php

[CHANGE] Migrate deprecated usage of 'pageinfo'

---

Classes/Command/CrawlerCommandController.php
Classes/Service/ProcessService.php

[BUGFIX] Change the calculation of composer-bin-dir (#416)

---

Classes/Controller/CrawlerController.php
Tests/Unit/Controller/CrawlerControllerTest.php

The interface and trait cleans up our crawler code.
Closes #421

[TASK] Use TYPO3 Logging API for CrawlerController

---

Classes/Controller/CrawlerController.php

This is not done yet, as we still cannot add Processes from backend.
But part of the problem is solved, there CommandController isn't throwing exceptions anymore.

[BUGFIX] Changed the QueryBuilder for the Delete,Select and Update to avoid conflicts

---

Classes/Backend/View/ProcessListView.php
Classes/Controller/CrawlerController.php
Classes/Domain/Repository/ProcessRepository.php

[BUGFIX] Make sure that Process is added and mapped correctly (#413)

---

Classes/Controller/CrawlerController.php

Needed this urgently so That commit shoud fix the issue.

[BUGFIX] https://github.com/AOEpeople/crawler/issues/307

---

Resources/Private/Templates/Backend/ShowCrawlerInformation.html

[BUGFIX] Make backend link to "go to log" work again

---

Classes/Backend/BackendModule.php
Classes/CrawlStrategy/SubProcessExecutionStrategy.php
Classes/Hooks/ProcessCleanUpHook.php
Classes/Service/ProcessService.php

- Use CommandUtility where applicable
- Remove usages for TYPO3_OS
Fixes #431

[TASK] Use CommandUtility API and Environment API

---

Classes/Controller/CrawlerController.php
Classes/Domain/Repository/ProcessRepository.php
Tests/Functional/Controller/CrawlerControllerTest.php
Tests/Unit/Controller/CrawlerControllerTest.php

- Use proper (int) type-casting instead of intval() = faster
- Use $this->tableName instead of 'tx_crawler_queue'
- Use $this->backendUser instead of $GLOBALS[BE_USER]
- Remove unused HTML styling code
- Move CLI_checkIfProcessIsActive into ProcessRepository

[TASK] Clean up code in CrawlerController

---

Classes/Domain/Repository/QueueRepository.php
Tests/Functional/Domain/Repository/QueueRepositoryTest.php

[BUGFIX] Populate Queue object before returning it from repository (#473)

---

Classes/Controller/CrawlerController.php
Tests/Functional/Controller/CrawlerControllerTest.php
Tests/Functional/Fixtures/pages.xml
Tests/Functional/Fixtures/tt_content.xml

[FEATURE] add _RECURSIVE option to the subpartParams Configuration of the lookup _TABLE instructions (#476)

---

Classes/Domain/Model/Configuration.php

[BUGFIX] Match force ssl property in model with tca

---

Classes/Command/ProcessQueueCommand.php
Classes/Task/CrawlMultiProcessTaskAdditionalFieldProvider.php

[FIX] cast variable types to comply strict_types

---

Classes/Backend/BackendModule.php
Classes/Hooks/IndexedSearchCrawlerHook.php
Tests/Unit/Domain/Model/ReasonTest.php

[BUGFIX] Add missing type casts (#504)

---

Classes/Backend/BackendModule.php

[BUGFIX] Add default values if $resFeVars is not set (#528)

---

Classes/Backend/BackendModule.php
Classes/Middleware/CrawlerInitialization.php
Documentation/Configuration/ExtensionManagerConfiguration/Index.rst
Documentation/Troubleshooting/Index.rst
cli/bootstrap.php

[BUGFIX] Check if indexes are set before using the in bootstrap.php (#481)

---

Classes/Backend/BackendModule.php

[BUGFIX] Switch to EXT:core locallang_core.xlf for V10 compatibility (#535)

---

Classes/Utility/PhpBinaryUtility.php
Tests/Functional/Utility/PhpBinaryUtilityTest.php

[TASK] Improves getPhpBinary and adds tests (#544)

---

CHANGELOG.md
Classes/Domain/Model/Process.php
Tests/Unit/Domain/Model/ProcessTest.php

[BUGFIX] Have getTimeForFirstItem and getTimeForLastItem return 0 if no process found

---

CHANGELOG.md
Classes/Backend/BackendModule.php
Classes/Command/BuildQueueCommand.php
Classes/Controller/CrawlerController.php
Classes/Converter/JsonCompatibilityConverter.php
Classes/Middleware/FrontendUserAuthenticator.php
Classes/QueueExecutor.php
Documentation/Troubleshooting/Index.rst
Tests/Functional/Api/CrawlerApiTest.php
Tests/Unit/Converter/JsonCompatibilityConverterTest.php

[WIP] json_encode instead of serialize data before writte to db.

---

CHANGELOG.md
Documentation/Features/Hooks/Index.rst

Add an example for the pageVeto hook.
Additionally:
- Name files where to register the hooks
- Use namespaced class for registration of pageVeto hook
**I have**

[DOCS] Add example for pageVeto hook

---

Classes/Hooks/IndexedSearchCrawlerHook.php
Tests/Unit/Hook/IndexedSearchCrawlerHookTest.php

[WIP][TASK] Enabled tests for IndexedSearchCrawlerHook set fixed timezone

---

crowdin.yml

The already translated files should not appear as to be translated
in Crowdin.
**I have**

[TASK] Ignore translated files in Crowdin

---

Tests/Unit/Hooks/DataHandlerHookTest.php
Tests/Unit/Hooks/IndexedSearchCrawlerHookTest.php

Add working addFlushedPages test

Add working test for DataHandlerHook

---

Documentation/Features/PriorityCrawling/Index.rst

Show the labels nicely in generated documentation.
**I have**

[DOCS] Correct usage of guilabel role

---

Classes/CrawlStrategy/CrawlStrategy.php
Classes/CrawlStrategy/GuzzleExecutionStrategy.php
Classes/CrawlStrategy/SubProcessExecutionStrategy.php
Tests/Unit/CrawlStrategy/SubProcessExecutionStrategyTest.php

This PR add a CrawlStategyInface that Guzzle and SubProcessExecutions implements, to ensure the two stategies follows the requirements.
**I have**

[TASK] Add CrawlStategy interface to Guzzle and SubProcess Execution

---

CHANGELOG.md
Classes/Controller/CrawlerController.php
Classes/Service/UrlService.php
Tests/Functional/Controller/CrawlerControllerTest.php
Tests/Functional/Service/UrlServiceTest.php

Url service

---

CHANGELOG.md
Classes/Hooks/DataHandlerHook.php
Tests/Unit/Hooks/DataHandlerHookTest.php

[BUGFIX] Ensure that DataHandlerHook will not add pages to queue that does not exist

---

.travis.yml
phpstan-baseline.neon
phpstan.neon

PHPStan is not allowed to fail anymore

[CI] Add PHPStan baseline to have more value for new code

---

Documentation/Configuration/Examples/News/Index.rst

Adjust tx_news example, change description of used pids
**I have**

[DOC] Update Documentation - correct pid descriptions in news example

---

CHANGELOG.md
Documentation/Configuration/ConfigurationRecords/Index.rst
Documentation/UseCases/CacheWarmup/Index.rst

Improve documentation, fix issue described in #639 
**I have**
(sorry, I didn't know that I should add a description in CHANGELOG.md. Furthermore was it the first time I added somethin in reST -  so I hope it's okay how it's made)

[DOC] Update Documentation regarding Cache WarmUp and UserGroups

---

.devbox/composer.json
.editorconfig
.travis.yml

Adds CodeCeption tests for TYPO3 10.4 as well.

[TASK] Add TYPO3 10.4 to behaviour tests too

---

CHANGELOG.md
Classes/Backend/RequestForm/LogRequestForm.php
Configuration/RequestMiddlewares.php
phpstan-baseline.neon

[WIP] Test different middleware registration order

---

Tests/Functional/Domain/Repository/ConfigurationRepositoryTest.php

[TASK] Add tests for ConfigurationRepository

---

Documentation/ExecutingTheQueue/BuildingAndExecutingQueueRightAway(fromCli)/Index.rst

Better explanation of the `--depth` parameter.
**I have**

[DOCS] Improve explanation of depth parameter

---

.gitignore
CHANGELOG.md
Resources/Private/Php/Libraries/composer.json
composer.json
ext_localconf.php

[BUGFIX] Auto-loading for non-composer projects fixed

---

.github/scripts/composer-require-check.php
.github/workflows/Requirement.yml
composer.json

[CI] Add Check for composer requirements for non-composer projects

---

CHANGELOG.md
Classes/Service/UrlService.php
Tests/Functional/Api/CrawlerApiTest.php
Tests/Functional/Command/BuildQueueCommandTest.php
Tests/Functional/Service/UrlServiceTest.php

Resovles: #579
**I have**
- [] Added tests for the new code

[CLEANUP] Remove all references to cHash

---

Classes/Controller/CrawlerController.php
phpstan-baseline.neon

[TASK] Remove obsolete ifs + adding early returns

---

CHANGELOG.md
Classes/Backend/RequestForm/LogRequestForm.php

[BUGFIX] Flush entire queue

---

CHANGELOG.md
Classes/Controller/CrawlerController.php
phpstan-baseline.neon

[BUGFIX] Check PageRow['uid'] before handing it on to next function

---

CHANGELOG.md
Classes/Controller/CrawlerController.php
Migrations/Code/ClassAliasMap.php
phpstan-baseline.neon

[DEPRECATE] CrawlerController->CLI_runHooks() is marked as deprecated

---

CHANGELOG.md
Classes/Api/CrawlerApi.php
Classes/Controller/CrawlerController.php
Classes/Hooks/DataHandlerHook.php
Classes/Service/ConfigurationService.php
Classes/Service/QueueService.php
Tests/Unit/Hooks/DataHandlerHookTest.php
Tests/Unit/Service/ConfigurationServiceTest.php
composer.json
phpstan-baseline.neon

[DEPRECATE] Class CrawlerApi

---

Classes/Domain/Repository/QueueRepository.php
Classes/Service/ConfigurationService.php

[TASK] Switch from count to empty() for array

---

CHANGELOG.md
Classes/Utility/SignalSlotUtility.php
phpstan-baseline.neon

[DEPRECATE] SignalSlotUtility to be removed in v11.x

---

CHANGELOG.md
Classes/Backend/RequestForm/StartRequestForm.php
phpstan-baseline.neon

[BUGFIX] PageTS Crawler Configurations not visible/selectable

---

CHANGELOG.md
Documentation/Configuration/ConfigurationRecords/Index.rst
Documentation/Configuration/PageTsconfigReference(txCrawlercrawlercfg)/Index.rst

[DOC] Exteneded example for PageTS configuration

---

.github/workflows/MutationTests.yml
Classes/Backend/Helper/ResultHandler.php
Classes/Controller/CrawlerController.php
Classes/Converter/JsonCompatibilityConverter.php
Classes/Domain/Model/Process.php
Classes/Domain/Model/ProcessCollection.php
Classes/Hooks/IndexedSearchCrawlerHook.php
Tests/Unit/Backend/BackendModuleTest.php
Tests/Unit/Controller/CrawlerControllerTest.php
Tests/Unit/Converter/JsonCompatibilityConverterTest.php
Tests/Unit/Domain/Model/ProcessCollectionTest.php
Tests/Unit/Domain/Model/ProcessTest.php
Tests/Unit/Domain/Repository/ProcessRepositoryTest.php
Tests/Unit/Hooks/IndexedSearchCrawlerHookTest.php
phpstan-baseline.neon

[TASK] Improved tests with respect to feedback from Infection PHP

---

Classes/Backend/RequestForm/LogRequestForm.php
Classes/Backend/RequestForm/StartRequestForm.php
Classes/Controller/CrawlerController.php
phpstan-baseline.neon

[CLEANUP] Remove internal use of deprecated functions

---

Tests/Functional/Command/FlushQueueCommandTest.php
Tests/Functional/Command/ProcessQueueCommandTest.php

[TASK] Add CommandTests to Coverage

---

.github/workflows/MutationTests.yml
Tests/Functional/Backend/RequestForm/LogRequestFormTest.php
Tests/Functional/Backend/RequestForm/MultiProcessRequestFormTest.php
Tests/Functional/Backend/RequestForm/RequestFormFactoryTest.php
Tests/Functional/Backend/RequestForm/StartRequestFormTest.php
Tests/Functional/Controller/CrawlerControllerTest.php
Tests/Functional/Fixtures/Resources/Layouts/BackendModule.html
Tests/Functional/Fixtures/Resources/Templates/Standard/ShowCrawlerInformation.html
Tests/Functional/Service/ProcessServiceTest.php
Tests/Unit/Controller/CrawlerControllerTest.php
Tests/Unit/FileWriter/CsvWriter/CrawlerCsvWriterTest.php
Tests/Unit/Service/ProcessServiceTest.php
Tests/Unit/Utility/MessageUtilityTest.php
Tests/Unit/Utility/PhpBinaryUtilityTest.php
Tests/Unit/Writer/FileWriter/CsvWriter/CrawlerCsvWriterTest.php
phpstan-baseline.neon

[TEST] Improve tests by add and moving from Functional to Unit to have them included in Mutation Tests

---

CHANGELOG.md
Classes/Command/ProcessQueueCommand.php
Classes/Controller/CrawlerController.php

[DEPRECATE] CrawlerController->CLI_releaseProcesses

---

.devbox/.ddev/config.yaml

This PR fixes issues inside the ddev devbox.
This solves #703
**I have**

[BUGFIX] Make devbox work again - Changed order of ddev commands

---

CHANGELOG.md
Classes/Controller/CrawlerController.php

This is a regression of commit:
https://github.com/AOEpeople/crawler/commit/2299e9900b4a6c938387b0afe6a4b4f9f04f89b1
Resolves #714

[BUGFIX] buildQueue with `--mode exec` resulted in a 503

---

CHANGELOG.md
Classes/CrawlStrategy/SubProcessExecutionStrategy.php
phpstan-baseline.neon

fixes #711 
add condition to get rid of null as result

add condition to get rid of null as result

---

.github/workflows/Tests.yml

[CI] Adjust version matrix to excluded php 7.2,7.3 from dev-master

---

.github/workflows/Acceptance.yml
.github/workflows/MutationTests.yml
.github/workflows/Requirement.yml
.github/workflows/StaticAnalysis.yaml
.github/workflows/Tests.yml

[CI] Change when acceptance tests are running

---

.github/workflows/Tests.yml
Classes/Backend/RequestForm/LogRequestForm.php
Tests/Functional/Backend/RequestForm/StartRequestFormTest.php
Tests/Functional/BackendRequestTestTrait.php
Tests/Functional/Command/BuildQueueCommandTest.php
Tests/Functional/Controller/CrawlerControllerTest.php
Tests/Functional/Hooks/ProcessCleanUpHookTest.php
Tests/Unit/Domain/Model/QueueTest.php
phpstan-baseline.neon

[TASK] Add BackendRequestTestTrait.php to help testing in TYPO3 ^11.0

---

CHANGELOG.md
Configuration/TCA/tx_crawler_configuration.php

[BUGFIX] Remove required from processing_instruction_filter in tx_crawler_configuration

---

Classes/Command/BuildQueueCommand.php
Classes/Command/FlushQueueCommand.php
Classes/Command/ProcessQueueCommand.php

[GCL] Adjust Command Options to repected types

---

CHANGELOG.md
Classes/Backend/RequestForm/LogRequestForm.php
Resources/Private/Templates/Backend/ShowLog.html

Changes how the Immediate is parsed for queue entries
Resolves: #728 
**I have**

[BUGFIX] Changes date parsing for immediate queue entries

---

Classes/Backend/RequestForm/LogRequestForm.php
Tests/Unit/Service/ProcessServiceTest.php
composer.json
phpstan-baseline.neon
rector-ci.php

[CI] Fix rector to specific version 0.10.6

---

.github/workflows/ci.yml

[CI] Set Ubuntu-18.04 for tests

---

.github/workflows/Tests.yml
Classes/Configuration/ExtensionConfigurationProvider.php
composer.json
ecs.php
phpstan-baseline.neon
phpstan.neon

[CI] Fix CI Problems

---

Classes/Controller/CrawlerController.php
Classes/Domain/Repository/ProcessRepository.php
Tests/Functional/Domain/Repository/ProcessRepositoryTest.php
phpstan-baseline.neon

[REFACTOR] Move addProcess logic to ProcessRepository

---

CHANGELOG.md
Classes/Api/CrawlerApi.php
Classes/Backend/BackendModule.php
Classes/Backend/RequestForm/LogRequestForm.php
Classes/ContextMenu/ItemProvider.php
Classes/Controller/CrawlerController.php
Classes/Domain/Repository/ConfigurationRepository.php
Classes/Domain/Repository/ProcessRepository.php
Classes/Domain/Repository/QueueRepository.php
Classes/Hooks/IndexedSearchCrawlerHook.php

[REFACTOR] Use constants for Repository Table Names

---

CHANGELOG.md
Classes/Controller/CrawlerController.php
Classes/Service/PageService.php
Tests/Unit/Controller/CrawlerControllerTest.php
Tests/Unit/Service/PageServiceTest.php
Tests/Unit/Service/VetoHookTestHelper.php
phpstan-baseline.neon

[REFACTOR] Add PageService to move checkIfPageShouldBeSkipped out of the CrawlerController

---

Classes/Command/ProcessQueueCommand.php
Classes/Domain/Model/Process.php

[TASK] Update Getters to also assign values

---

CHANGELOG.md
Classes/Middleware/CrawlerInitialization.php

[BUGFIX] Sites/URLs get crawled but not indexed

---

Classes/Controller/CrawlerController.php
Classes/Domain/Repository/QueueRepository.php
Classes/Service/ConfigurationService.php
Classes/Service/PageService.php
Tests/Functional/Service/ConfigurationServiceTest.php
Tests/Unit/Service/ConfigurationServiceTest.php
ecs.php

[CI] Update ECS Configuration

---

.github/scripts/composer-require-check.php
Resources/Private/Php/Libraries/composer.json

[BUGFIX] Correct Require Check script to match on PHP

---

.github/workflows/Acceptance.yml

[CI] Add branch to Acceptance Tests to ensure running again correct

---

Tests/Unit/Writer/FileWriter/CsvWriter/CrawlerCsvWriterTest.php

[TASK] Update tests to match the new more secure CsvUtility in TYPO3 Core

---

.github/workflows/Tests.yml

[CI] Add MySQL 5.7 to TYPO3 dev-master test

---

.devbox/composer.json
.github/workflows/Acceptance.yml

[CI] Update composer name for devbox

---

CHANGELOG.md
Configuration/Services.yaml

[TASK] Add description to crawler:commands for TYPO3 10+

---

CHANGELOG.md
Classes/Command/FlushQueueCommand.php
Documentation/ExecutingTheQueue/RunningViaCommandController/Index.rst
Tests/Functional/Command/FlushQueueCommandTest.php

!!! [TASK] Remove --page argument from FlushQueueCommand

---

CHANGELOG.md
Classes/Domain/Model/Process.php
Tests/Unit/Domain/Model/ProcessTest.php

!!! [TASK] Remove deprecated functions in Domain/Model/Process

---

CHANGELOG.md
Classes/Domain/Repository/QueueRepository.php
Tests/Functional/Domain/Repository/QueueRepositoryTest.php
phpstan-baseline.neon

!!! [TASK] Remove deprecated functions in Domain/Repository/QueueRepository

---

CHANGELOG.md
Classes/Service/ProcessService.php
Tests/Unit/Service/ProcessServiceTest.php
phpstan-baseline.neon

!!! [TASK] Remove deprecated functions in ProcessService

---

.devbox/.ddev/config.yaml

[DEVBOX] Update MariaDB to 10.5

---

composer.json

[DEP] Update psalm dependency

---

composer.json

[DEP] Update phpstan-typo3 dependency

---

Tests/Unit/ContextMenu/ItemProviderTest.php

[TASK] Added tests for ContextMenu/ItemProvider

---

.devbox/.ddev/docker-compose.selenium.yaml
.github/workflows/Acceptance.yml
Tests/Acceptance/BackendModule/BackendModuleCest.php
Tests/Acceptance/Frontend/FrontendCest.php
Tests/Acceptance/Support/AcceptanceTester.php
Tests/Acceptance/Support/Step/Acceptance/Admin.php
Tests/Acceptance/Support/Step/Acceptance/BackendModule.php
Tests/Acceptance/_envs/v10-non-composer.yml
Tests/Acceptance/_envs/v11-non-composer.yml
Tests/Acceptance/_envs/v11p80-non-composer.yml

This resolves https://github.com/tomasnorre/crawler/issues/769

[CI] Add AcceptanceTests for non-composer TYPO3 11

---

Classes/Service/QueueService.php
Classes/Service/UrlService.php
Tests/Functional/Api/CrawlerApiTest.php
Tests/Functional/Command/BuildQueueCommandTest.php
Tests/Functional/Service/UrlServiceTest.php
Tests/Functional/data/canCreateQueueEntriesUsingConfigurationRecord.xml
Tests/Functional/data/pages.xml
phpstan-baseline.neon

[CLEAN] Remove "unused" code from TYPO3 9 Support

---

Classes/Backend/RequestForm/LogRequestForm.php
Classes/Backend/RequestForm/MultiProcessRequestForm.php
Tests/Functional/Backend/RequestForm/LogRequestFormTest.php
Tests/Functional/Backend/RequestForm/MultiProcessRequestFormTest.php
Tests/Functional/Fixtures/Resources/Templates/Standard/ShowLog.html

[CI] Add more tests for Backend/RequestForms

---

Classes/Controller/CrawlerController.php
Tests/Functional/Command/BuildQueueCommandTest.php
Tests/Unit/Value/QueueRowTest.php
phpstan-baseline.neon

Add Tests for Value/QueueRow

---

CHANGELOG.md
Documentation/Troubleshooting/Index.rst

[DOCS] Add toubleshooting about Site Config baseVariants not used

---

.github/workflows/BackwardCompabilityCheck.yml
Classes/Controller/CrawlerController.php
composer.json
infection.json.dist

[CI] Update infection to ^0.25

---

CHANGELOG.md
Classes/Controller/CrawlerController.php
Classes/Service/ConfigurationService.php

Fix some undefined array key errors in PHP8 in CrawlerController and ConfigurationService.
**I have**

[BUGFIX] Fix some undefined array keys in PHP8

---

CHANGELOG.md
Classes/Middleware/CrawlerInitialization.php
Classes/Middleware/FrontendUserAuthenticator.php

Fix some undefined array keys in PHP8 when running the queue.
**I have**

[BUGFIX] Fix some undefined array keys in PHP8 in middlewares

---

.github/workflows/Acceptance.yml

This includes the remote repositories to ensure Acceptance tests works on PRs
Solves: #784

[CI] Add remote repository to ensure Acceptance tests running on PRs

---

.github/workflows/BackwardCompabilityCheck.yml
composer.json
phpstan-baseline.neon

CI: Update nikic-parser + psalm

---

composer.json
infection.json.dist

[CI] Update infection to ^0.26

---

.gitignore
Classes/Converter/JsonCompatibilityConverter.php
Classes/Utility/TcaUtility.php
Tests/Unit/Converter/JsonCompatibilityConverterTest.php
Tests/Unit/CrawlStrategy/CrawlStrategyFactoryTest.php
Tests/Unit/Domain/Model/ProcessCollectionTest.php
Tests/Unit/Domain/Model/ProcessTest.php
Tests/Unit/Service/PageServiceTest.php
Tests/Unit/Service/UrlServiceTest.php
Tests/Unit/Utility/TcaUtilityTest.php
infection.json.dist

[TASK] Update/Add tests

---

.devbox/.ddev/docker-compose.volume.yaml
.devbox/composer.json
.github/workflows/Acceptance.yml

[CI] Update Devbox setup to suit CI better

---

.Docker/docker-compose.yml
.github/scripts/composer-require-check.php
.github/workflows/DBMS.yml
Build/nimut-testing-framework-postgresql.patch
Classes/Api/CrawlerApi.php
Classes/Controller/CrawlerController.php
Classes/Domain/Repository/ConfigurationRepository.php
Classes/Domain/Repository/ProcessRepository.php
Classes/Domain/Repository/QueueRepository.php
Tests/Functional/Api/CrawlerApiTest.php
Tests/Functional/Controller/CrawlerControllerTest.php
Tests/Functional/Domain/Repository/ConfigurationRepositoryTest.php
Tests/Functional/Domain/Repository/ProcessRepositoryTest.php
Tests/Functional/Domain/Repository/QueueRepositoryTest.php
Tests/Functional/Fixtures/tx_crawler_queue.xml
Tests/Unit/Controller/CrawlerControllerTest.php
composer.json
ecs.php

[CI] Add additional DBMS tests to CI

---

.github/workflows/SonarCloud.yml

Add missing phpunit-merger to SonarCloud Action

---

composer.json

[TASK] Normalize composer with ergebnis/composer-normalize

---

Tests/Functional/Middleware/CrawlerInitializationTest.php
Tests/Unit/Middleware/CrawlerInitializationTest.php

[CI] Add tests for CrawlerInitialization Middleware

---

Classes/CrawlStrategy/CrawlStrategyFactory.php
Tests/Unit/Controller/CrawlerControllerTest.php
Tests/Unit/CrawlStrategy/CrawlStrategyFactoryTest.php
Tests/Unit/CrawlStrategy/SubProcessExecutionStrategyTest.php
Tests/Unit/Hooks/DataHandlerHookTest.php
Tests/Unit/Service/ConfigurationServiceTest.php
Tests/Unit/Utility/PhpBinaryUtilityTest.php

[TASK] Hardening tests

---

CHANGELOG.md
Classes/Controller/CrawlerController.php

[TASK] Fixed regression from commit-id: a89889f

---

CHANGELOG.md
Resources/Private/Templates/Backend/ProcessOverview.html

[TASK] Remove obsolete columns from ProcessOverview

---

CHANGELOG.md
Classes/Command/ProcessQueueCommand.php
phpstan-baseline.neon

!!! [TASK] Switch constants in ProcessQueueCommand from public to private

---

CHANGELOG.md
Classes/CrawlStrategy/CrawlStrategyFactory.php
Classes/CrawlStrategy/CrawlStrategyInterface.php
Classes/CrawlStrategy/GuzzleExecutionStrategy.php
Classes/CrawlStrategy/SubProcessExecutionStrategy.php
Classes/QueueExecutor.php
phpstan-baseline.neon

!!! [TASK] Add interface to CrawlStrategy filename

---

CHANGELOG.md
Tests/Functional/Command/ProcessQueueCommandTest.php

!!! [TASK] Remove property queueRepository from ProcessQueueCommandTest

---

CHANGELOG.md
Classes/Domain/Repository/ProcessRepository.php
Tests/Functional/Domain/Repository/ProcessRepositoryTest.php

!!! [TASK] Remove countActive from ProcessRepository

---

CHANGELOG.md
Classes/Domain/Repository/ConfigurationRepository.php
Tests/Functional/Domain/Repository/ConfigurationRepositoryTest.php
phpstan-baseline.neon

!!! [TASK] Remove getCrawlerConfigurationRecords() from ConfigurationRepository

---

CHANGELOG.md
Classes/Middleware/FrontendUserAuthenticator.php

!!! [TASK] Remove queueRepository property from FrontendUserAuthenticator

---

.github/workflows/Tests.yml
CHANGELOG.md
Classes/Utility/TcaUtility.php
Resources/Private/Php/Libraries/composer.json
Tests/Functional/Utility/TcaUtilityTest.php
Tests/Unit/Utility/TcaUtilityTest.php
composer.json

!!! [TASK] Switch getExtensionIcon() in TcaUtility from protected to private

---

CHANGELOG.md
Classes/Backend/RequestForm/LogRequestForm.php
Classes/Backend/RequestForm/MultiProcessRequestForm.php
Classes/Backend/RequestForm/RequestFormInterface.php
Classes/Backend/RequestForm/StartRequestForm.php
phpstan-baseline.neon

!!! [TASK] Add Type Hint for id parameters on RequestForm render method

---

CHANGELOG.md
Classes/Domain/Repository/QueueRepository.php
Tests/Functional/Domain/Repository/QueueRepositoryTest.php
phpstan-baseline.neon

This resolves some of the issues in #894, NOT ALL. 
**I have**

!!! [TASK] Remove deprecated functions from QueueRepository

---

CHANGELOG.md
Classes/Domain/Repository/ProcessRepository.php
Tests/Functional/Domain/Repository/ProcessRepositoryTest.php
phpstan-baseline.neon

!!! [TASK] Remove findByProcessId from ProcessRepository

---

Classes/Command/ProcessQueueCommand.php
Configuration/Services.yaml
Tests/Functional/Command/ProcessQueueCommandTest.php

[TASK] Cleanup ProcessQueueCommand

---

Classes/Backend/RequestForm/LogRequestForm.php
Classes/Command/ProcessQueueCommand.php
Classes/Controller/CrawlerController.php
Classes/Service/ConfigurationService.php
phpstan-baseline.neon

[TASK] Cleanup phpstan-baseline.neon

---

CHANGELOG.md
Classes/Middleware/CrawlerInitialization.php
Classes/Middleware/FrontendUserAuthenticator.php
Tests/Unit/Middleware/FrontendUserAuthenticatorTest.php

!!! [TASK] Switch runPollSuccessHooks() and isRequestHashMatchingQueueRecord() to be private

---

.gitignore
CHANGELOG.md
Classes/Service/ConfigurationService.php
Tests/Functional/Service/ConfigurationServiceTest.php
Tests/Unit/Service/ConfigurationServiceTest.php
infection.json.dist
phpstan-baseline.neon

[TASK] Cleanup Configuration Service

---

Classes/Helper/Sleeper/NullSleeper.php
Classes/Helper/Sleeper/SystemSleeper.php
Tests/Unit/Service/ConfigurationServiceTest.php

[TASK] Add test to ConfigurationService

---

Documentation/Configuration/Examples/News/Index.rst

This PR updates an example I had myself previously added.
Resolves: [#938](https://github.com/tomasnorre/crawler/issues/938)
**I have**

[TASK] Update example in documentation

---

Classes/Backend/RequestForm/LogRequestForm.php
Classes/Backend/RequestForm/StartRequestForm.php
Classes/ContextMenu/ItemProvider.php
Classes/Domain/Repository/QueueRepository.php
Classes/Middleware/FrontendUserAuthenticator.php
Classes/Service/QueueService.php
phpstan-baseline.neon

[CGL] Cleanup PHPStan baseline

---

.github/workflows/StaticAnalysis.yaml
.gitignore
.phive/phars.xml
composer.json

[CI] Move psalm to phive

---

Classes/Domain/Repository/ConfigurationRepository.php
Classes/Domain/Repository/ProcessRepository.php
Classes/Domain/Repository/QueueRepository.php
phpstan-baseline.neon

This is related to the to-dos from #825 
**I have**

[TASK] Switch to new DBAL functions in Repositories

---

.github/workflows/Tests.yml

[CI] Add PHP7.4 for scrutinizer coverage upload

---

CHANGELOG.md
Classes/Command/ProcessQueueCommand.php
phpstan-baseline.neon

[TASK] Remove CLI_hooks from ProcessQueueCommand

---

.github/workflows/Coveralls.yml

[CI] Switch to php-coveralls/php-coveralls for PHP 8 support 

---

.scrutinizer.yml

[CI] Update Scrutinizer to PHP 8.0

---

composer.json

[DEV] Update Code Ception Dependencies

---

CHANGELOG.md
ext_localconf.php

[BUGFIX] If indexed_search is installed activate procInstructions for indexed_search

---

Classes/Backend/RequestForm/LogRequestForm.php
Classes/Backend/RequestForm/StartRequestForm.php
Classes/Configuration/ExtensionConfigurationProvider.php
Classes/Controller/CrawlerController.php
Classes/Domain/Repository/ProcessRepository.php
Classes/Middleware/FrontendUserAuthenticator.php
Classes/Service/ConfigurationService.php
Tests/Functional/Service/ProcessServiceTest.php
composer.json
ecs.php
phpstan-baseline.neon

[DEV] Update symplify/easy-coding-standard dependency

---

CHANGELOG.md
Classes/Backend/RequestForm/MultiProcessRequestForm.php
Classes/Hooks/CrawlerHookInterface.php
Classes/Hooks/ProcessCleanUpHook.php

!!! [TAKS] CrawlerHookInterface doesn't take a CrawlerController as input anymore

---

.github/workflows/DBMS.yml
.github/workflows/Tests.yml
CHANGELOG.md
Classes/Backend/RequestForm/LogRequestForm.php
ext_localconf.php
phpstan-baseline.neon

[BUGFIX] Ensure undefined indexes is not throwing a warning in PHP 8

---

phpstan.neon

[CI] Update PHPStan config to include Type Coverage

---

Classes/Command/BuildQueueCommand.php
Tests/Unit/Service/ProcessServiceTest.php

This is a "cherry-pick" for the main branch, after it's got released in the v11.x-branch.
**I have**

[BUGFIX] Check that array key is set before using (PHP 8.1)

---

.devbox/composer.json
.github/workflows/Acceptance.yml
.github/workflows/Tests.yml
Tests/Functional/Utility/TcaUtilityTest.php
composer.json

[CI] Allow TYPO3 12 in CI tests and composer.json

---

.github/workflows/Acceptance.yml
.github/workflows/Tests.yml
CHANGELOG.md
Classes/Command/BuildQueueCommand.php
Classes/Command/FlushQueueCommand.php
Classes/Command/ProcessQueueCommand.php
Classes/Controller/CrawlerController.php
Classes/CrawlStrategy/CallbackExecutionStrategy.php
Classes/CrawlStrategy/CrawlStrategyFactory.php
Classes/CrawlStrategy/CrawlStrategyInterface.php
Classes/CrawlStrategy/GuzzleExecutionStrategy.php
Classes/CrawlStrategy/SubProcessExecutionStrategy.php
Classes/Event/AfterQueueItemAddedEvent.php
Classes/Event/AfterUrlAddedToQueueEvent.php
Classes/Event/AfterUrlCrawledEvent.php
Classes/Event/BeforeQueueItemAddedEvent.php
Classes/Event/InvokeQueueChangeEvent.php
Classes/Event/ModifySkipPageEvent.php
Classes/Exception/CommandNotFoundException.php
Classes/Exception/CrawlerObjectException.php
Classes/Exception/ExtensionSettingsException.php
Classes/Exception/NoIndexFoundException.php
Classes/Exception/ProcessException.php
Classes/Exception/TimeStampException.php
Classes/Helper/Sleeper/SleeperInterface.php
Classes/Hooks/CrawlerHookInterface.php
Classes/Middleware/CrawlerInitialization.php
Classes/Middleware/FrontendUserAuthenticator.php
Classes/Writer/FileWriter/CsvWriter/CsvWriterInterface.php
composer.json

[TASK] Add support for PHP 8.2

---

CHANGELOG.md
Classes/Command/BuildQueueCommand.php
Classes/Command/FlushQueueCommand.php
Classes/Command/ProcessQueueCommand.php
Classes/Controller/CrawlerController.php
Classes/CrawlStrategy/CallbackExecutionStrategy.php
Classes/CrawlStrategy/CrawlStrategyFactory.php
Classes/CrawlStrategy/CrawlStrategyInterface.php
Classes/CrawlStrategy/GuzzleExecutionStrategy.php
Classes/CrawlStrategy/SubProcessExecutionStrategy.php
Classes/Event/AfterQueueItemAddedEvent.php
Classes/Event/AfterUrlAddedToQueueEvent.php
Classes/Event/AfterUrlCrawledEvent.php
Classes/Event/BeforeQueueItemAddedEvent.php
Classes/Event/InvokeQueueChangeEvent.php
Classes/Event/ModifySkipPageEvent.php
Classes/Exception/CommandNotFoundException.php
Classes/Exception/CrawlerObjectException.php
Classes/Exception/ExtensionSettingsException.php
Classes/Exception/NoIndexFoundException.php
Classes/Exception/ProcessException.php
Classes/Exception/TimeStampException.php
Classes/Helper/Sleeper/SleeperInterface.php
Classes/Hooks/CrawlerHookInterface.php
Classes/Middleware/CrawlerInitialization.php
Classes/Middleware/FrontendUserAuthenticator.php
Classes/Writer/FileWriter/CsvWriter/CsvWriterInterface.php

!!![TASK] Mark all classes internal

---

.github/workflows/Acceptance.yml
.github/workflows/AutoComment.yml.txt
.github/workflows/DBMS.yml
.github/workflows/GithubServer.yml.txt
.github/workflows/Greetings.yml
.github/workflows/Tests.yml

Fix: Wrapping

---

.github/workflows/BackwardCompatibilityCheck.yml
.github/workflows/Deploy.yml
.github/workflows/GithubServer.yml.txt
.github/workflows/MutationTests.yml
.github/workflows/Requirement.yml
.github/workflows/SonarCloud.yml
.github/workflows/StaticAnalysis.yaml

Enhancement: Update `actions/cache`

---

Classes/Controller/Backend/AbstractBackendModuleController.php
Classes/Controller/Backend/BackendModuleCrawlerLogController.php
Classes/Controller/Backend/BackendModuleCrawlerProcessController.php
Classes/Controller/Backend/BackendModuleStartCrawlingController.php
Classes/Controller/CrawlerController.php
Classes/Service/BackendModuleHtmlElementService.php
Classes/Service/BackendModuleLinkService.php
Classes/Service/BackendModuleLogService.php
Classes/Writer/FileWriter/CsvWriter/CrawlerCsvWriter.php
Configuration/Services.yaml
Resources/Private/Templates/Backend/ShowLog.html
Tests/Acceptance/BackendModule/BackendModuleCest.php
Tests/Functional/Controller/Backend/BackendModuleStartCrawlingControllerTest.php
Tests/Functional/Domain/Repository/QueueRepositoryTest.php
Tests/Functional/Service/BackendModuleHtmlElementServiceTest.php
Tests/Functional/Service/BackendModuleLinkServiceTest.php
Tests/Functional/Service/BackendModuleLogServiceTest.php
composer.json
phpstan.neon

[TASK] Cleanup BackendModule Controllers

---

CHANGELOG.md

[TASK] Update CHANGELOG.md

---

.devbox/.ddev/config.yaml
.github/workflows/Acceptance.yml
.github/workflows/BackwardCompatibilityCheck.yml
.github/workflows/DBMS.yml
.github/workflows/MutationTests.yml
.github/workflows/Requirement.yml
.github/workflows/StaticAnalysis.yaml
.github/workflows/Tests.yml

[CI] Setup CI for v11.x branch to be enable to do 11.x releases

---

Classes/Service/ConfigurationService.php
Classes/Service/UrlService.php

CI: Fix psaml

---

Classes/Service/ProcessService.php

Cleanup: Remove TYPO3 v10 Only Code

---

.devbox/.ddev/.gitignore
.devbox/.ddev/config.yaml
.devbox/composer.json
.devbox/config/system/additional.php
.editorconfig
.github/workflows/Acceptance.yml
Classes/Utility/HookUtility.php
composer.json

Update ddev config

---

Classes/Converter/JsonCompatibilityConverter.php
Classes/Middleware/FrontendUserAuthenticator.php
Tests/Functional/Command/BuildQueueCommandTest.php
Tests/Functional/Service/BackendModuleLogServiceTest.php
Tests/Functional/SiteBasedTestTrait.php
composer.json
phpstan-baseline.neon

Fix BackendModuleLogServiceTests

---

CHANGELOG.md
Classes/Controller/CrawlerController.php
Classes/Service/ProcessInstructionService.php
Tests/Unit/Service/ProcessInstructionServiceTest.php
phpstan-baseline.neon

ProcessInstructionService

---

.devbox/.ddev/docker-compose.selenium.yaml
Tests/Acceptance/BackendModule/BackendModuleCest.php
Tests/Acceptance/BackendModule/CrawlerConfigurationCest.php
Tests/Acceptance/Support/Step/Acceptance/Admin.php
Tests/Acceptance/Support/Step/Acceptance/BackendModule.php
composer.json

This PR brings the Acceptance tests close to green again, only one test is still failing. 
Still way better than no tests. 
**I have**

CI: Update Selenium Images + Small test adjustments.

---

.github/workflows/Acceptance.yml
CHANGELOG.md
README.md
composer.json

Add PHP 8.3 support

---

.devbox/.ddev/config.yaml
CHANGELOG.md
Classes/Crawler.php
Tests/Unit/CrawlerTest.php

[BUGFIX] Ensure lock directory for enabling/disabling crawler exists

---

.github/workflows/Acceptance.yml
.github/workflows/BackwardCompatibilityCheck.yml
.github/workflows/Coveralls.yml
.github/workflows/DBMS.disabled
.github/workflows/Deploy.yml
.github/workflows/GithubServer.yml.txt
.github/workflows/MutationTests.yml
.github/workflows/Requirement.yml
.github/workflows/SonarCloud.yml
.github/workflows/StaticAnalysis.yaml
.github/workflows/Tests.yml

CI: Update GitHub Actions Cache and Checkout to v4

---

Classes/Domain/Repository/ProcessRepository.php
Classes/Domain/Repository/QueueRepository.php
Tests/Functional/Command/BuildQueueCommandTest.php
Tests/Functional/Domain/Repository/ProcessRepositoryTest.php
Tests/Functional/Middleware/FrontendUserAuthenticatorTest.php

[CI] Fix BuildQueueCommandTests

---

.github/workflows/DBMS.yml

[CI] Add additional postgreSQL and MariaDB versions

---

.github/workflows/Tests.yml

[CI] Add PHP 8.2 and 8.3 tests back

---

Tests/Functional/Service/BackendModuleLogServiceTest.php

Fix timestamps in Tests

---

Classes/Controller/Backend/AbstractBackendModuleController.php
Classes/Controller/Backend/BackendModuleCrawlerLogController.php
Classes/Controller/Backend/BackendModuleCrawlerProcessController.php
Classes/Controller/Backend/BackendModuleStartCrawlingController.php
Tests/FunctionalTests.xml
Tests/Unit/ContextMenu/ItemProviderTest.php
Tests/Unit/Controller/CrawlerControllerTest.php
Tests/Unit/Converter/JsonCompatibilityConverterTest.php
Tests/Unit/CrawlStrategy/GuzzleExecutionStrategyTest.php
Tests/Unit/Domain/Model/ReasonTest.php
Tests/Unit/Event/AfterUrlCrawledEventTest.php
Tests/Unit/Event/BeforeQueueItemAddedEventTest.php
Tests/Unit/Event/ModifySkipPageEventTest.php
Tests/Unit/Middleware/FrontendUserAuthenticatorTest.php
Tests/Unit/Service/ProcessServiceTest.php
Tests/Unit/Service/UrlServiceTest.php
Tests/Unit/Utility/MessageUtilityTest.php
Tests/Unit/Value/QueueFilterTest.php
Tests/Unit/Value/QueueRowTest.php
Tests/UnitTests.xml
Tests/phpunit.xml
phpstan-baseline.neon
phpstan.neon

Set random order for unit, functional and mutation tests, to ensure that tests a independent of each other.
Resolves #1050
**I have**

[CI] Set random order for tests

---

Tests/Functional/Service/BackendModuleLinkServiceTest.php

This Harding some tests, to avoid checking for css classes that might change from core.
Resolves #1035
**I have**

[CI] Harding Tests

---

Tests/Unit/Controller/CrawlerControllerTest.php
Tests/Unit/Controller/Helper/ResultHandlerTest.php
Tests/Unit/Converter/JsonCompatibilityConverterTest.php
Tests/Unit/CrawlStrategy/CallbackExecutionStrategyTest.php
Tests/Unit/CrawlStrategy/GuzzleExecutionStrategyTest.php
Tests/Unit/Domain/Model/ConfigurationTest.php
Tests/Unit/Domain/Model/ProcessCollectionTest.php
Tests/Unit/Domain/Model/ProcessTest.php
Tests/Unit/Domain/Model/QueueTest.php
Tests/Unit/Domain/Model/ReasonTest.php
Tests/Unit/Event/AfterQueueItemAddedEventTest.php
Tests/Unit/Event/AfterUrlAddedToQueueEventTest.php
Tests/Unit/Event/BeforeQueueItemAddedEventTest.php
Tests/Unit/Event/InvokeQueueChangeEventTest.php
Tests/Unit/Event/ModifySkipPageEventTest.php
Tests/Unit/Middleware/CrawlerInitializationTest.php
Tests/Unit/Service/ProcessInstructionServiceTest.php
Tests/Unit/Service/ProcessServiceTest.php
Tests/Unit/Service/UrlServiceTest.php
Tests/Unit/Service/UserServiceTest.php
Tests/Unit/Value/CrawlActionTest.php
Tests/Unit/Value/QueueFilterTest.php
Tests/Unit/Value/QueueRowTest.php
Tests/Unit/Writer/FileWriter/CsvWriter/CrawlerCsvWriterTest.php

Switches from tearDown to ResetSingleton Property, I like that approach better.
**I have**

[TASK] Switch to resetSingleton property instead of tearDown

---

.github/workflows/BackwardCompatibilityCheck.yml

[CI] Update roave/backward-compatibility-check

---

CHANGELOG.md
Classes/Middleware/FrontendUserAuthenticator.php

[BUGFIX] Prevent undefined array key uid and username in FrontendUserAuthentication

---

Resources/Private/Php/Libraries/composer.json
Tests/Unit/Middleware/FrontendUserAuthenticatorTest.php
composer.json

[TASK] Update composer dependencies

---

Classes/Configuration/ExtensionConfigurationProvider.php
Classes/ContextMenu/ItemProvider.php
Classes/Controller/Backend/BackendModuleStartCrawlingController.php
Classes/Controller/CrawlerController.php
Classes/CrawlStrategy/SubProcessExecutionStrategy.php
phpstan-baseline.neon

[TASK] Cleanup PHPStan Baseline

---

composer.json

[CI] Fix call of @test:set-vars in composer.json

---

CHANGELOG.md
Classes/Middleware/FrontendUserAuthenticator.php

Resolves #1031 backport. 
**I have**

[BUGFIX] Check queueRec before usage to avoid PHP errors

---

.devbox/.ddev/config.yaml
Tests/Acceptance/Frontend/FrontendCest.php

[CI] Add Search test

---

Classes/Domain/Model/ProcessCollection.php
Classes/Middleware/CrawlerInitialization.php
Classes/Middleware/FrontendUserAuthenticator.php
Classes/Service/BackendModuleLinkService.php
Classes/Service/BackendModuleLogService.php
Classes/Service/UrlService.php
Tests/Unit/Converter/JsonCompatibilityConverterTest.php

[TASK] Update CodeStyle for use-statements

---

Tests/Functional/Domain/Repository/QueueRepositoryTest.php
Tests/Functional/Service/BackendModuleLogServiceTest.php
Tests/Unit/Controller/CrawlerControllerTest.php
Tests/Unit/Controller/Helper/ResultHandlerTest.php
Tests/Unit/Service/ConfigurationServiceTest.php
Tests/Unit/Service/PageServiceTest.php

[TASK] Remove PHPUnit Test Deprecations from Functional Tests

---

phpstan-baseline.neon

[CI] Update PHPStan baseline

---

.github/workflows/Acceptance.yml
.github/workflows/GithubServer.yml.txt
CHANGELOG.md
Classes/Controller/Backend/BackendModuleCrawlerProcessController.php
Classes/Service/BackendModuleLinkService.php
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Backend/ProcessOverview.html
Tests/Acceptance/BackendModule/CrawlerCest.php
ecs.php

[FEATURE] Posible to flush processes from backend

---

Tests/Acceptance/BackendModule/CrawlerCest.php

BUGFIX: Update label in acceptance test

---

CHANGELOG.md
Classes/Command/BuildQueueCommand.php

Gives info when a pages doesn't exits
Resolves #1097
**I have**

[FEATURE] Inform when pages does not exists when calling crawler:buildQueue from cli

---

CHANGELOG.md
Classes/Service/PageService.php

Disallow DOKTYPE_BE_USER_SECTION to be crawled.
Resolves #1100 
**I have**

[FEATURE] Disallow DOKTYPE_BE_USER_SECTION

---

Classes/Command/BuildQueueCommand.php

Improve output for crawler:buildQueue command

---

CHANGELOG.md
Classes/Writer/FileWriter/CsvWriter/CrawlerCsvWriter.php

CrawlerCsvWriter::CARRIAGE_RETURN constant is now private

CrawlerCsvWriter::CARRIAGE_RETURN constant is now private

---

Classes/Controller/CrawlerController.php
Classes/EventListener/AfterQueueItemAddedEventListener.php
Configuration/Services.yaml
Tests/Functional/EventListener/AfterQueueItemAddedEventListenerTest.php

Add eventlistener for AfterQueueItemAddedEvent to move some code out where is doesn't belong.
Resolves #1106 
**I have**

feature: switch to event listener internally

---

.gitignore
Classes/Helper/Sleeper/SystemSleeper.php
Tests/Functional/Configuration/ExtensionConfigurationProviderTest.php
Tests/Functional/ContextMenu/ItemProviderTest.php
Tests/Unit/Helper/SystemSleeperTest.php
Tests/Unit/Hooks/DataHandlerHookTest.php

ci: add more tests

---

Classes/Command/BuildQueueCommand.php
Classes/Command/ProcessQueueCommand.php
Configuration/Services.yaml
Tests/Functional/Command/BuildQueueCommandTest.php
Tests/Functional/Command/ProcessQueueCommandTest.php
phpstan-baseline.neon

[TASK] Refactor commands

---

Classes/Command/BuildQueueCommand.php

[TASK] Remove internal ref for CrawlerController

---

.github/workflows/Acceptance.yml
CHANGELOG.md
cli/conf.php

[TASK] Remove cli/conf.php as it is not used since a long time

---

CHANGELOG.md
Classes/Controller/CrawlerController.php

This PR fixes the crawling of mount pages.
**I have**

[BUGFIX] fix crawling of mount pages

---

CHANGELOG.md
Classes/Service/QueueService.php
Classes/Utility/HookUtility.php
Configuration/Services.yaml
Tests/Functional/Service/QueueServiceTest.php

fix: Ensure that pages are added to queue when page cache is cleared

---

CHANGELOG.md
Classes/Controller/CrawlerController.php
Tests/Unit/Controller/CrawlerControllerTest.php
phpstan-baseline.neon

fix: Ensure pageRow uid is set before trying to add to queue

---

CHANGELOG.md
Documentation/UseCases/IndexedSearch/Index.rst

Documentation how to setup crawler with indexed_search to re-index all pages at night.
Tested on TYPO3 v11.5.41 and crawler 11.0.11.
Resolves: https://github.com/tomasnorre/crawler/issues/558
**I have**

[DOCS] Setup How-To for indexed_search + crawler

---

CHANGELOG.md
Classes/Converter/JsonCompatibilityConverter.php
Classes/CrawlStrategy/CrawlStrategyInterface.php
Classes/CrawlStrategy/GuzzleExecutionStrategy.php
Classes/CrawlStrategy/SubProcessExecutionStrategy.php
Classes/QueueExecutor.php
Tests/Unit/Converter/JsonCompatibilityConverterTest.php
Tests/Unit/CrawlStrategy/GuzzleExecutionStrategyTest.php
Tests/Unit/Domain/Model/ProcessTest.php
Tests/Unit/Service/ProcessServiceTest.php
phpstan-baseline.neon

Guzzle error warning2

---

Classes/Controller/Backend/Helper/ResultHandler.php
phpstan-baseline.neon

Cleanup ResultHandler, there were errros in PHPStan that could be easily fixed
**I have**

[TASK] Cleanup ResultHandler

---

Classes/Controller/Backend/BackendModuleCrawlerLogController.php
Classes/Controller/Backend/BackendModuleStartCrawlingController.php
Classes/Controller/Backend/Helper/UrlBuilder.php
phpstan-baseline.neon

Cleanup PHPStan reported errors. 
**I have**

[TASK] Cleanup UrlBuilder

---

Classes/Writer/FileWriter/CsvWriter/CrawlerCsvWriter.php
phpstan-baseline.neon

Cleanup PHPStan CSVWriter errors
**I have**

[TASK] Cleanup CSVWriter

---

Classes/Controller/CrawlerController.php
phpstan-baseline.neon

Small cleanup of the CrawlerController, no need to check if process_id is set, it can be set to empty if not set. 
**I have**

[TASK] Remove obsolete check in CrawlerController
