- class.tx_crawler_lib.php
Fixes issue #40
According to this page: https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.0/Breaking-61785-LoadTcaFunctionRemoved.html this function call can be removed completely.
> [TASK] Remove usage of invalid functions

- hooks/class.tx_crawler_hooks_processCleanUp.php
Verify that $results is an array before iterating over it, as exec_SELECTgetRows
may also return NULL
Resolves: #47
> [BUG] Regression - Crawler cannot create new processes

- modfunc1/class.tx_crawler_modfunc1.php
Create a simple method to generate the correct URLs
Resolves #56
> [BUGFIX] Links on refresh icon/queue id do not work in TYPO3 7.6

- .travis.yml
- class.tx_crawler_lib.php
- composer.json
Resolves issue #8 
I've added the CLI_deleteProcessMarkedDeleted() to keep the process list smaller and therefor the slow query problem should be solved.
> [TASK] Deleting old tx_crawler_processes entries ends up in slow query

- Configuration/TCA/Overrides/tx_crawler_configuration.php
- Configuration/TCA/tx_crawler_configuration.php
this removes deprecation warnings in TYPO3 7.6
> replace deprecated function call in TCA file, add renderType for select fields

- cli/class.tx_crawler_cli.php
- cli/class.tx_crawler_cli_flush.php
- cli/class.tx_crawler_cli_im.php
Some cli classes throw a deprecation notice using PHP 7 because they are not using __construct as constructor method name.
Core: Error handler (BE): PHP Runtime Deprecation Notice: Methods with the same name as their class will not be constructors in a future version of PHP; tx_crawler_cli_im has a deprecated constructor in typo3conf/ext/crawler/cli/class.tx_crawler_cli_im.php line 38
> #107 Fixes deprecated notices

- Classes/Utility/SchedulerUtility.php
Resolves #144 #143 
- This is not only about crawler tasks, but every type of scheduler task
> [BUGFIX] Not possible to add new scheduler tasks after upgrade to 5.1.0 (#144)

- class.tx_crawler_lib.php
When an exception is thrown during crawling - e.g. because a hook throws one - it was caught without notice. This cost me 6 hours of debugging.
Now it is shown in debug output.
> Show exception message

- Configuration/TCA/tx_crawler_configuration.php
- class.tx_crawler_lib.php
- modfunc1/class.tx_crawler_modfunc1.php
Make the extension work with TYPO3 CMS 8.x (8.6.0 especially):
* fix broken language label references
* remove invalid displayCondition "FALSE"
* replace IconUtility with IconFactory for 8.0.0 and above
* remove call to removed methods
> [BUGFIX] 8.x compatibility

- modfunc1/class.tx_crawler_modfunc1.php
remove removed spacer method call 
see https://docs.typo3.org/typo3cms/extensions/core/7.6/Changelog/7.6/Deprecation-71153-DocumentTemplateSpacer.html
> remove removed spacer method call

- Classes/Event/EventDispatcher.php
The array-index is undefined if the checked event has no observers.
This leads to a warning with PHP 7.2, because count() must only be used
on arrays or objects which implements Countable.
> [BUGFIX] Check if key exists before using count()

- ext_tables.php
Many core labels are gone in TYPO3 7.6 because the path for `locallang_core.php` and `locallang_general.php` was changed in EXT:crawler 6.0.
This fix will define an alternative location for the two files.
Note: I copied and adapted this fix from EXTnews. Credits for the solution go to @georgringer. Thank you!
> [BUGFIX] Fix missing locallang labels for TYPO3 7.6

- composer.json
The `branch-alias` should point to a dev version which is always higher than the last release. Otherwise, a custom source for the package is ignored because it is older than upstream...
> [TASK] Change branch-alias for dev-master to 6.1.x-dev

- class.tx_crawler_lib.php
TYPO3 CMS expects this file to exist, see #262.
The real issue will be fixed by adding a hook to TYPO3 CMS.
Until this happens, the following hotfix will apply.
> [BUGFIX] Create file which is expected by TYPO3 CMS

- Classes/Controller/CrawlerController.php
Class 'language' is deprecated since 6.0 and removed with 7.0.
This patch replaces the old 'language' class name usage
with LanguageService.
> [BUGFIX] Replace old class name for LanguageService

- Configuration/TCA/tx_crawler_configuration.php
feInterface-section in TCA configuration is deprecated since 6.0 and removed with 6.2.
See also: https://docs.typo3.org/typo3cms/TCAReference/6.0/Reference/Feinterface/Index.html
> [CLEANUP] Remove obsolete TCA feInterface config

- Classes/Backend/BackendModule.php
If $q_entry['result_data'] is empty it will trigger an PHP Warning on unset.
>  [BUGFIX] Avoid warning if $q_entry['result_data'] is empty

- Classes/Controller/CrawlerController.php
Change was not needed as it is deprecated.
Resolves #341
> [BUGFIX] Adjust getConfigurationKeys to match old usages

- composer.json
The package requires the PHP extension »posix« to be installed
on the system. The posix extension however is not available for Windows.
This causes failed installations of crawler on Windows systems.
Only suggest the installation of the extension and dont make it
a requirement anymore to allow installations on both Unix and Windows.
Refs #384
> [BUG] Composer: Move system dependency

- Documentation/ExtCrawler/Configuration/ConfigurationRecords/Index.rst
Appareantlythere is a "hidden" feature that allows you to exclude pages recursively.
The feature is **so old** that it is not even documented in the source code.
> [DOCS] Document page exclude recursiveness

- template/process/list.php
I'm getting errors in backend in "Crawling Processes" view because of non-existing methods. This PR fixes that.
> [BUGFIX] Use correct method names

- Classes/Controller/CrawlerController.php
A minor typo leads to PHP error (method not found).
The PR fixes the database query / method call.
Closes: #423
> [BUGFIX] Fix typo in queryBuilder

- Classes/Controller/CrawlerController.php
This patch cleans up CrawlerController in some areas:
- remove unused cli_* methods and properties
- Use TYPO3 v9 Core API (Environment API)
- use PHP7 methods for hook-array checks instead of is_array()
- Use !empty() instead of count() to avoid possible PHP 7.2 issues
- Intantiate TSFE properly, similar to as done in EXT:redirects
- Avoid "global $TYPO3_CONF_VARS" and "global $TCA"
- Proper return statements where requested by phpdoc
- Remove usage of LanguageService fallback ($LANG is always available if in BE/CLI context)
Closes: #425
> [TASK] Clean up CrawlerController

- Classes/Controller/CrawlerController.php
- Tests/Functional/Api/CrawlerApiTest.php
- Tests/Functional/Domain/Repository/ProcessRepositoryTest.php
- Tests/Unit/Controller/CrawlerControllerTest.php
- ext_conf_template.txt
The option "logFile" is not needed, as now the logger API
is taking care of logging into various channels.
Fixes: #435
> [!!!][TASK] Remove logFile extension configuration setting

- Classes/Backend/BackendModule.php
- Classes/Controller/CrawlerController.php
- Classes/Domain/Repository/ConfigurationRepository.php
- Tests/Unit/Controller/CrawlerControllerTest.php
Fetching crawler configuration from the database and the according URL building process is a bit cleaner now:
- Fetching configuration from the rootline is now in a separate method. Easier for mocking in tests
- The method parseParams() has been replaced by GeneralUtility:: explodeUrl2Array()
- URL generation for variants of a page ID has been streamlined and building more easily
- Minor foreach / array checks are simplified
This is a precursor to streamline further URL compilation changes
> [TASK] Streamline Configuration fetching and URL building

- Classes/Controller/CrawlerController.php
- Configuration/TCA/tx_crawler_configuration.php
- Documentation/Configuration/ConfigurationRecords/Index.rst
- Documentation/Configuration/PageTsconfigReference(txCrawlercrawlercfg)/Index.rst
- Resources/Private/Language/Backend.xlf
- Tests/Functional/Api/CrawlerApiTest.php
- Tests/Functional/Fixtures/tx_crawler_configuration.xml
- Tests/Functional/SiteBasedTestTrait.php
- Tests/Functional/data/canCreateQueueEntriesUsingConfigurationRecord.xml
- Tests/Functional/data/pages.xml
- ext_tables.sql
When using Site Handling in TYPO3 v9, pages with a site component now receive a baseUrl from the current site where the page is located on.
Using Site Handling's PageRouter functionality, the cHash is then automatically added when needed.
In addition to that, when having no site configuration (which is only the case when dealing with RealURL v9 forks) the cHash is then automatically calculated.
For this case, the option "tx_crawler_configuration.cHash" is removed without substitution, to follow TYPO3 Core's pattern to have TYPO3 Core deal with cHash generation then.
> [!!!][FEATURE] Automatically calculate cHash and Base URL via Site Handling

- Classes/Controller/CrawlerController.php
- Classes/Domain/Model/Configuration.php
- Classes/Utility/BackendUtility.php
- Configuration/TCA/tx_crawler_configuration.php
- Resources/Private/Language/Backend.xlf
- Tests/Functional/Api/CrawlerApiTest.php
- Tests/Functional/Fixtures/tx_crawler_configuration.xml
- Tests/Functional/data/canCreateQueueEntriesUsingConfigurationRecord.xml
- ext_tables.php
- ext_tables.sql
Evaluating TSFE and the sys_template record is not needed anymore,
as Frontend requests are called externally (Direct via SubRequest or via Guzzle),
so this option can be removed without substitution.
Along with the change the Configuration Model class is cleaned up with
only the properties needed.
> [!!!][TASK] Remove root_template_pid option

- Classes/Service/ProcessService.php
The last compatible version of EXT:typo3_console with TYPO3 7 LTS is v4.9.6, which stores the typo3cms script in the sub-folder `Scripts/`.
This patch distinguishes between EXT:typo3_console versions before and after v5 when resolving the 
`$scriptPath` in non-composer mode installations.
> [BUGFIX] Resolve typo3cms non-composer path for typo3_console < v5

- .travis.yml
- Classes/Api/CrawlerApi.php
- Classes/Command/BuildQueueCommand.php
- Classes/Command/FlushQueueCommand.php
- Classes/Command/ProcessQueueCommand.php
- Classes/Controller/CrawlerController.php
- Classes/CrawlStrategy/GuzzleExecutionStrategy.php
- Classes/Domain/Model/Configuration.php
- Classes/Domain/Repository/ConfigurationRepository.php
- Classes/Domain/Repository/QueueRepository.php
- Classes/Middleware/CrawlerInitialization.php
- Classes/QueueExecutor.php
- Classes/Worker/CrawlerWorker.php
- Tests/Functional/Domain/Repository/ProcessRepositoryTest.php
- Tests/Functional/Domain/Repository/QueueRepositoryTest.php
- Tests/Unit/Controller/CrawlerControllerTest.php
- composer.json
- rector-ci.yaml
Based on @rectorphp [start contest](https://twitter.com/rectorphp/status/1196711403333332992) I send my first PR :) more are comming. Step by step.
**Feature:** adds first Rector run to CI.
The coding style was fixed somehow automatically.
The `"prefer-stable": true` in `composer.json` is best practise for development with dev dependencies (`"minimum-stability": "dev"`), so you always works with the same dependencies as the end user. It also speeds up composer install/update brutally.
> [CI] Add Rector CI

- Documentation/Troubleshooting/Index.rst
That's to avoid possible SQL error after extension update.
> Add update instructions to troubleshooting docs

- CONTRIBUTERS.md
- Classes/Api/CrawlerApi.php
- Classes/Command/BuildQueueCommand.php
- Classes/Controller/CrawlerController.php
- Documentation/Configuration/PageTsconfigReference(txCrawlercrawlercfg)/Index.rst
- Documentation/ExecutingTheQueue/RunningViaCommandController/Index.rst
- Tests/Functional/Api/CrawlerApiTest.php
- Tests/Functional/Controller/CrawlerControllerTest.php
- Tests/Functional/Domain/Repository/ConfigurationRepositoryTest.php
- Tests/Functional/Domain/Repository/QueueRepositoryTest.php
- Tests/Functional/Fixtures/pages.xml
- Tests/Functional/Fixtures/tt_content.xml
- Tests/Functional/Fixtures/tx_crawler_configuration.xml
- Tests/Functional/Fixtures/tx_crawler_queue.xml
Applying my patch [eef0c94] to the typo3v9 branch was easy. Fixing some bugs that prevented me from testing the new table based parameter expansion and applying 2 change sets (18.07.19 [98605ee], 22.07.19 [e17ec22]) that were required for automated testing was the harder part.
Pleas have a look especially  at the changes of the methods getConfigurationsForBranch() and getDuplicateRowsIfExist () of the class CrawlerController in commit [91e88fc]. I changed them in in a way that the fulfil the test cases from the TYPO3 v8 (current master) branch , but I'm not sure if this is intended.
> [FEATURE] add _RECURSIVE option to the subpartParams Configuration of the lookup _TABLE instructions (#479)

- Configuration/RequestMiddlewares.php
The initialisation of the crawler has to be performed before the page resolver kicks in. otherwise the fe user groups could not be set and the page resolver responses a 403 for restricted pages.
> [BUGFIX] Load crawler initialization before page resolver

- Classes/Middleware/CrawlerInitialization.php
Currently the fe user group list is not indexed.
indexed_search reads the ids from the `frontend.user`, `groupIds` aspect. 
See https://github.com/TYPO3-CMS/indexed_search/blob/v9.5.13/Classes/Indexer.php#L308
The groups are not stored in the aspect currently, so the default groups `0,-1` are indexed, what's wrong.
This PR fixes the indexing if there are fe groups defined.
Currently there is no setter for the groups in the aspect, so i think we has to create a new user aspect.
The 0 and -2 has to be set to the group too, like the getter does. See https://github.com/TYPO3/TYPO3.CMS/blob/v9.5.13/typo3/sysext/core/Classes/Context/UserAspect.php#L134
> [BUGFIX] Set user aspect with fe groups during indexing

- Classes/Command/BuildQueueCommand.php
When i don't add the optional option `conf` a PHP Type Error are thrown, becouse `$conf` becomes `null` instead of string:
```text
trim() expects parameter 1 to be string, null given 
thrown in file typo3conf/ext/crawler/Classes/Command/BuildQueueCommand.php 
in line 200
```
This PR fixes the problem by casting the `conf` option into a string.
The command i use to reproduce this:
```bash
bin/typo3 crawler:buildQueue -p 2 -d 99 -m queue
```
> [BUGFIX] Fix type error in build queue command

- Classes/Middleware/CrawlerInitialization.php
- Classes/Middleware/FrontendUserAuthenticator.php
- Configuration/RequestMiddlewares.php
The frontend usergroup needs to be set before the typo3/cms-frontend/page-resolver is processed. At that time the TSFE controller isn't initialized yet, so the TSFE configuration needs to be done at a later point.
> Separate middleware initialization

- composer.json
The branch alias was removed recently in edca84df2cacdaf89a8cbc47fcb20ed9a6f17c22. However, as development continues in the master branch, this is still needed but now with reference to `dev-master`. Additionally, the alias version should be variable `9.0.x-dev` instead of the hardcoded `9.0.0-dev`.
> [TASK] Add branch alias for 9.0.x-dev in composer

- Classes/Middleware/FrontendUserAuthenticator.php
Setting the $frontendUser with $request->getAttribute('frontend.user') resulted in a \stdClass
Since this middleware is called after the core fe_user authenticator we can assume an instance of FrontendUserAuthentication is set in $GLOBALS['TSFE']->fe_user
> [FIX] get fe_user from $GLOBALS['TSFE']

- CHANGELOG.md
- Classes/CrawlStrategy/GuzzleExecutionStrategy.php
This case can occur, when the connection is resetted from the server.
Resolves: #587
Related: #584
> [BUGFIX] Handle empty response when fetching URL

- .gitattributes
Files and folders which are defined as export-ignore are not
included in an archive and therefore not installed via composer
on production systems.
> [TASK] Introduce .gitattributes

- Classes/Controller/CrawlerController.php
With TYPO3 10.4 the limitation of custom doktypes to a number less
than 200 was lifted. This patch makes it possible to crawl on custom
doktypes with a number greater than 200.
See also:
- https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-18079-PagesdoktypeRestrictionForFrontendQueriesRefined.html
- https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Domain/Repository/PageRepository.php#L103
> [TASK] List specific doktypes for skipping page

- Classes/Command/BuildQueueCommand.php
- Classes/Command/FlushQueueCommand.php
- Classes/Command/ProcessQueueCommand.php
The descriptions are shown in the overview of available commands when
vendor/bin/typo3 is called without any parameter.
> [TASK] Add description to commands

- CHANGELOG.md
- Classes/Controller/CrawlerController.php
The type error "strcmp() expects parameter 1 to be string, null given" was
raised when using a PageTS configuration without "procInstrFilter" defined
(at least under PHP 7.4).
> [BUGFIX] Set default value when procInstrFilter is not defined

- CHANGELOG.md
- Configuration/Commands.php
- Configuration/Services.yaml
In TYPO3 v10+ commands are configured in Configuration/Services.yaml with dependency
injection tags. To keep backward compatibility with TYPO3 v9 the old configuration
in Configuration/Commands.php is kept.
This avoids deprecation notices in TYPO3 v10 and makes the configuration future-proof.
See also: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-89139-AddDependencyInjectionSupportForConsoleCommands.html
> [TASK] Configure commands in Services.yaml

- .editorconfig
- .gitignore
- Documentation/Aoe/Aoe.rst
- Documentation/Configuration/ConfigurationRecords/Index.rst
- Documentation/Configuration/ExtensionManagerConfiguration/Index.rst
- Documentation/Configuration/HttpAuthentication/Index.rst
- Documentation/Configuration/Index.rst
- Documentation/Configuration/PageTsconfigReference(txCrawlercrawlercfg)/Index.rst
- Documentation/ExecutingTheQueue/BuildingAndExecutingQueueRightAway(fromCli)/Index.rst
- Documentation/ExecutingTheQueue/ExecutingQueueWithCron-job/Index.rst
- Documentation/ExecutingTheQueue/Index.rst
- Documentation/ExecutingTheQueue/RunViaBackend/Index.rst
- Documentation/ExecutingTheQueue/RunningViaCommandController/Index.rst
- Documentation/Features/Hooks/Index.rst
- Documentation/Features/Index.rst
- Documentation/Features/MultiprocessSupport/Index.rst
- Documentation/Features/PollableProcessingInstructions/Index.rst
- Documentation/Includes.txt
- Documentation/Index.rst
- Documentation/Introduction/Index.rst
- Documentation/Introduction/Screenshots/Index.rst
- Documentation/Introduction/WhatDoesItDo/Index.rst
- Documentation/Links/Links.rst
- Documentation/Scheduler/Index.rst
- Documentation/Troubleshooting/Index.rst
- Documentation/UseCases/CacheWarmup/Index.rst
- Documentation/UseCases/Index.rst
- Remove "coding: utf-8 -*- with BOM" -> in practise it is without BOM
- Use Includes.txt on every page to avoid doubling roles
- Structure headers correctly
- Use "figure" with caption where appropriate
- Use "vendor/bin/typo3" throughout the document for unity
- Adjust .editoconfig: Show line length at 80 chars (e.g. in PhpStorm) and define indentation at 3 chars (like in core documentation)
- git-ignore generated documentation
> [TASK] Revise documentation syntax

- Resources/Private/Language/Backend.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/locallang_csh_tx_crawler_configuration.xlf
Crowdin doesn't show the information stored in the attribute "id".
If it should be visible, the attribute must be duplicated using
"resname".
find Resources/Private/Language/ -name '*.xlf' -exec sed -i -e \
'/resname/!s/\(<trans-unit id="\)\([^"]*\)"/\1\2" resname="\2"/' \
'{}' +
Additionally, the attribute "original" is filled with the path of the translation
file instead of dummy value "messages". This string is also shown in Crowdin
and helps users while translating.
**I have**
> [TASK] Add resname attribute to trans-unit tags in XLF files

- CHANGELOG.md
- Configuration/RequestMiddlewares.php
In #527 the position of the crawler initialisation has changed to before `typo3/cms-frontend/output-compression`.  
In my installation this is too late and no indexing will be performed for cached pages.
The initialisation must be performed before `typo3/cms-frontend/prepare-tsfe-rendering`. 
At the `typo3/cms-frontend/prepare-tsfe-rendering` middleware the nocache checks are performed and the indexed_search TSFE hook to disable the caching kicks in. 
indexed_search needs the crawler initialisation to disable the cache for the request at this point
> [BUGFIX] Load crawler initialization before tsfe rendering preparation

- CONTRIBUTING.md
Xdebug can be enabled with a ddev command on-the-fly. This is now reflected in the Contributing documentation.
**I have**
> [DOCS] Use "ddev xdebug on" command to activate xdebug

- CHANGELOG.md
- Classes/Controller/CrawlerController.php
- Tests/Functional/Controller/CrawlerControllerTest.php
This makes sure that PageUid added with excludeStrings are kept as Integers.
Resolves: #625
**I have**
> [BUGFIX] Make sure PageUid added with ExcludeString is kept as integer

- CHANGELOG.md
- Classes/Api/CrawlerApi.php
- Classes/Backend/BackendModule.php
This PR fixed the initiation of ProcessRepository and QueueRepository, switching from new to GeneralUtiltiy::makeInstance()
**I have**
> [BUGFIX] Switched to GeneralUtility::makeInstance for ProcessRepository and QueueRepository

- CHANGELOG.md
- Classes/Command/BuildQueueCommand.php
- Classes/Controller/CrawlerController.php
- Tests/Functional/Command/BuildQueueCommandTest.php
Adds a simple Symfony progress bar when using the execute mode to have a visual representation of the crawling progress.
Also removed some dead code from the command since the configuration keys are always returend as array. Fixed a wrong PHPDoc return type in CrawlerController as well.
Resolves #627 partially.
**I have**
> [FEATURE] Add progress bar to BuildQueueCommand

- CHANGELOG.md
- Classes/Backend/BackendModule.php
This changes the parameters for single and detailed view in process overview. This ensure that the toggle from simple to detailed view and vice versa is working again.
**I have**
> [BUGFIX] Change params to have simple and detailed process-view work again

- CHANGELOG.md
- Classes/Domain/Model/Process.php
- Classes/Domain/Repository/ProcessRepository.php
This PR resolves #637 
With the getQueueRepository() we makes sure that the $this->queueRepository is always set when needed.
**I have**
> [BUGFIX] Makes sure the QueueRepository is always set when needed in Domain/Model/Process

- CHANGELOG.md
- Classes/Middleware/FrontendUserAuthenticator.php
- phpstan-baseline.neon
Resolves #643 
After 9.1.0 a regression was introduce, so that the Frontend User wasn't correct initialized on Crawler with FE-Groups.
This PR takes care of that both TYPO3 9 LTS and 10 LTS is supported.
**I have**
> [BUGFIX] Add back FE-Group initiation for TYPO3 9LTS

- CHANGELOG.md
- Classes/Backend/RequestForm/LogRequestForm.php
- Classes/Command/FlushQueueCommand.php
- Classes/Controller/CrawlerController.php
- Classes/Domain/Repository/QueueRepository.php
- Classes/Value/QueueFilter.php
- Tests/Functional/Command/FlushQueueCommandTest.php
- Tests/Functional/Controller/CrawlerControllerTest.php
- Tests/Functional/Domain/Repository/QueueRepositoryTest.php
- Tests/Unit/Value/QueueFilterTest.php
- phpstan-baseline.neon
This PR adds a QeueuFilter ValueObject to work with Objects instead of strings and arrays when handling the QueueFilters, on FlushQueue etc.
**I have**
> [REFACTOR] Add QueueFilter Object to operate with Object instead of string/arrays

- CHANGELOG.md
- Classes/Command/ProcessQueueCommand.php
- Classes/Controller/CrawlerController.php
- Classes/Domain/Repository/QueueRepository.php
- Tests/Functional/Controller/CrawlerControllerTest.php
- Tests/Functional/Domain/Repository/QueueRepositoryTest.php
- phpstan-baseline.neon
This moves the GetDuplicateRowIfExists to the QueueRepository where it belongs. 
The one in CrawlerController is marked as deprecated. 
Resolves #376 
**I have**
> [REFACTOR] Move GetDuplicateRowIfExists to the QueueRepository

- cli/bootstrap.php
Resolves #662: Bug in cli command 'crawler:processQueue' related to 'trustedHostsPattern'
> [BUGFIX] Assign port as string to $_SERVER['port'] in cli/bootstrap.php

- CHANGELOG.md
- Classes/Command/BuildQueueCommand.php
- Tests/Functional/Command/BuildQueueCommandTest.php
- phpstan-baseline.neon
Adds Error information when page 0 is used for crawler:buildQueue
Resolves: #649 
**I have**
> [TASK] Add error handling when page 0 is used for buildQueue

- composer.json
This PR adds the extension key inside composer.json
Providing the extension key inside composer.json is mandatory in future TYPO3 versions
**I have**
> [FIX] Added extension key into composer.json

- CHANGELOG.md
- ext_tables.sql
Default fields in `tx_crawler_configuration` are remove from
`ext_table.sql` as they are obsolete, will be added from TCA
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.3/Feature-85160-AutoCreateManagementDBFieldsFromTCACtrl.html
Resolves #710
> [CLEANUP] Remove auto-created fields in ext_tables.sql

- .devbox/composer.json
- .github/workflows/Acceptance.yml
Instead of requiring the changes via composer (which seems not to work for PRs) from the
dedicated branch use the already checked out sources.
The extension sources are then symlinked to .devbox/typo3conf/ext/crawler.
> [CI] Use path package of extension for acceptance tests

- Documentation/Configuration/PageTsconfigReference(txCrawlercrawlercfg)/Index.rst
Hi there, I recently searched for an option to crawl multiple news folders at once. Within the code I found the _RECURSIVE flag which is not explained in the documentation yet (https://docs.typo3.org/p/aoepeople/crawler/9.2/en-us/Configuration/PageTsconfigReference(txCrawlercrawlercfg)/Index.html).
> Explain _RECURSIVE flag in documentation

- .github/workflows/MutationTests.yml
- CHANGELOG.md
- Classes/Command/ProcessQueueCommand.php
- Classes/Controller/CrawlerController.php
- composer.json
- phpstan-baseline.neon
This PR Add the CLI_ functions from the CrawlerController to ProcessCommand, there are only used in there, so having the as private functions in there instead of a Service was more logical to me, but still not 100% sure if I like the service approach more to have the ProcessCommand smaller.
**I have**
> [REFACTOR] Add cli methods to ProcessCommand and deprecated them in CrawlerController

- CHANGELOG.md
- Classes/Controller/CrawlerController.php
When calling the buildQueue command, e.g.
`crawler:buildQueue 3 deployment --depth 99 --mode exec`
the following exception is thrown:
`
Uncaught TYPO3 Exception Argument 1 passed to AOE\Crawler\Service\ConfigurationService::expandExcludeString() must be of the type string, null given,
called in /var/www/xxx/releases/215/public/typo3conf/ext/crawler/Classes/Controller/CrawlerController.php on line 1359
thrown in file /var/www/xxx/releases/215/public/typo3conf/ext/crawler/Classes/Service/ConfigurationService.php
in line 169
` 
I have a configuration not as database record but as a TS confguration. Appearently, the "subcfg|exclude" key is not configured which leads to this error.
**Expected behavior/output**
No exception is thrown ;-)
**Steps to reproduce**
Call buildQueue as command with …
> [BUGFIX] Fix type error when exclude subcfg is not defined

- CHANGELOG.md
- Classes/Service/ConfigurationService.php
- Tests/Unit/Service/ConfigurationServiceTest.php
- phpstan-baseline.neon
> [BUGFIX] Avoid empty mountpoint parameter in URL when building the queue

- Configuration/TCA/tx_crawler_configuration.php
The TCA configuration `showRecordFieldList` inside the section `interface` is not evaluated anymore and all occurrences have been removed.
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-88901-RenderAllFieldsInElementInformationController.html
**I have**
> [TASK] Remove TCA configuration showRecordFieldList

- CHANGELOG.md
- Classes/Api/CrawlerApi.php
- Classes/Backend/RequestForm/LogRequestForm.php
- Classes/Controller/CrawlerController.php
- Classes/Domain/Repository/ConfigurationRepository.php
- Classes/Domain/Repository/ProcessRepository.php
- Classes/Domain/Repository/QueueRepository.php
- Classes/Hooks/IndexedSearchCrawlerHook.php
- Classes/Service/ConfigurationService.php
- phpstan-baseline.neon
https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/Installation/LegacyInstallation.html
https://github.com/TYPO3/typo3/blob/10.4/composer.lock#L220
> [BUGFIX] Switch back to fetch() instead of fetchAssociative to support legacy TYPO3 installations

- CHANGELOG.md
- Resources/Private/Templates/Backend/ShowLog.html
The text was not displayed in the confirm dialog in the backend module due to wrong translation keys.
**I have**
> [BUGFIX] Display text in confirm dialog in backend module

- CHANGELOG.md
- Classes/Backend/RequestForm/LogRequestForm.php
- Resources/Private/Templates/Backend/ShowLog.html
Resolves: #865
The patch fixes the error
“20.12.21 14:51” could not be parsed by \DateTime constructor: DateTime::__construct()
The dates are parsed already through BackendUtility::datetime() so the variable can be displayed unchanged.
**I have**
> [BUGFIX] Fix DateTime parse error in backend module when displaying log

- CHANGELOG.md
- Classes/Utility/TcaUtility.php
This PR fixes an undefined array key on PHP 80 when creating, updating or saving
a configuration record.
**I have**
> [BUGFIX] Fix undefined array key when creating configuration record

- Classes/Utility/BackendUtility.php
- Configuration/Icons.php
This improves the loading speed of every request in TYPO3 v11+.
In TYPO3 v10 the old way to register icons is used.
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-94692-RegisteringIconsViaServiceContainer.html
**I have**
> [TASK] Register icons via service container

- Classes/Api/CrawlerApi.php
- Classes/Backend/BackendModule.php
- Classes/Backend/RequestForm/LogRequestForm.php
- Classes/Command/BuildQueueCommand.php
- Classes/Command/FlushQueueCommand.php
- Classes/Command/ProcessQueueCommand.php
- Classes/Controller/CrawlerController.php
- Classes/Domain/Model/Process.php
- Classes/Hooks/ProcessCleanUpHook.php
- Classes/Service/ConfigurationService.php
- Classes/Service/ProcessService.php
- Tests/Functional/Api/CrawlerApiTest.php
- Tests/Functional/Command/BuildQueueCommandTest.php
- Tests/Functional/Command/FlushQueueCommandTest.php
- Tests/Functional/Domain/Repository/ConfigurationRepositoryTest.php
- Tests/Functional/Domain/Repository/ProcessRepositoryTest.php
- Tests/Functional/Domain/Repository/QueueRepositoryTest.php
- Tests/Functional/Hooks/ProcessCleanUpHookTest.php
- Tests/Functional/Service/ProcessServiceTest.php
- Tests/Functional/Service/QueueServiceTest.php
- Tests/Functional/Service/UrlServiceTest.php
- phpstan-baseline.neon
This PRs switched from ObjectManager->get() to GeneralUtility::makeInstace, as preparing for the switch to the Dependency Injection. 
**I have**
> [TASK] Switch from ObjectManager->get to GeneralUtility::makeInstance

- Classes/Command/ProcessQueueCommand.php
- ext_conf_template.txt
The descriptions for sleeptime and sleepafter where swapped (related to #515).
The unit for sleeptime is microseconds (used in usleep) not milliseconds (fixed in Command description and ext_conf_template.txt).
> Updated descriptions of command options

- Documentation/Configuration/Examples/News/Index.rst
A return terminates execution immediately so no further code is reached and executed.
**I have**
> Remove break after return in example

- composer.json
- ext_emconf.php
QueryBuilder->executeQuery() and ->executeStatement() were introduced on Jan 18th, 2022 with
https://github.com/TYPO3/typo3/commit/0d4fff93b5cf378357b9bfc1144d47df4787a1fc. The first
release providing the new methods was TYPO3 v11.5.6 on Feb 8th, 2022. As the main branch
of EXT:crawler now use these methods since https://github.com/tomasnorre/crawler/commit/9a04f114ffad9eac8b7ec7b4f800890225a2caa6, 
the minimum TYPO3 version is adjusted.
Additionally, as the minimum PHP version is now 8.0, but TYPO3 v11.5 can also be installed on
PHP 7.4, the PHP version constraint is added to ext_emconf.php.
> [TASK] Adjust minimum TYPO3 version to v11.5.6

- .github/workflows/Acceptance.yml
- .github/workflows/BackwardCompatibilityCheck.yml
- .github/workflows/Coveralls.yml
- .github/workflows/DBMS.yml
- .github/workflows/Deploy.yml
- .github/workflows/GithubServer.yml.txt
- .github/workflows/MutationTests.yml
- .github/workflows/Requirement.yml
- .github/workflows/SonarCloud.yml
- .github/workflows/StaticAnalysis.yaml
- .github/workflows/Tests.yml
This updates `actions/checkout` to `v3` as node 12 is deprecated.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
**I have**
> [CI] Switch to actions/checkout@v3

- CHANGELOG.md
- Classes/Command/BuildQueueCommand.php
Ensures that array key is set before used.
Resolves #984 
**I have**
> [BUGFIX] Check that array key is set before using (PHP 8.1)

- Classes/Service/ConfigurationService.php
Fixes the PHP 8.1 warning when "transOrigPointerField" doesn't exist in TCA for the given table
This PR fixes #989 
**I have**
> [BUGFIX] #989: Fixes PHP 8.1 transOrigPointerField warning

- Classes/Middleware/FrontendUserAuthenticator.php
Prevents undefined array key uid and username warnings in FrontendUserAuthentication middleware.
Resolves #1012 which blows up the sys_log on every requested login protected page in queue. 
Perhaps not the cleanest solution.
**I have**
> [BUGFIX] Prevent undefined array key uid and username in FrontendUserAuthentication

- CHANGELOG.md
- Configuration/RequestMiddlewares.php
(Backport of #1018 to v11.x)
History:
--------
Because of a problem with lochmueller/staticfilecache, crawler issue https://github.com/tomasnorre/crawler/issues/642 changed the middleware loading order to execute crawler after static file cache. (commit 0f7cb6abac4d8d6e228b0385665dc02f17cdfdcb)
The source of the problem was that the crawler CrawlerInitialization middleware overwrote the HTTP response that was generated by TYPO3.
Since commit 8a9b896721f479d7babc4bb5920536e8124a1797 (issue https://github.com/tomasnorre/crawler/issues/837) the HTTP response is not destroyed/overwritten by crawler anymore but moved into a HTTP header "X-T3Crawler-Meta".
The loading order does not influence compatibility with static file cache anymore.
Bug
---
The changed loading order in the bug fix led to …
> [BUGFIX] Fix middleware order for forced indexing (crawler 11)

- CHANGELOG.md
- Configuration/RequestMiddlewares.php
History:
--------
Because of a problem with lochmueller/staticfilecache, crawler issue https://github.com/tomasnorre/crawler/issues/642 changed the middleware loading order to execute crawler after static file cache. (commit 0f7cb6abac4d8d6e228b0385665dc02f17cdfdcb)
The source of the problem was that the crawler CrawlerInitialization middleware overwrote the HTTP response that was generated by TYPO3.
Since commit 8a9b896721f479d7babc4bb5920536e8124a1797 (issue https://github.com/tomasnorre/crawler/issues/837, version 11.0.1) the HTTP response is not destroyed/overwritten by crawler anymore but moved into a HTTP header "X-T3Crawler-Meta".
The loading order does not influence compatibility with static file cache anymore.
Bug
---
The changed loading order in the bug fix led to the problem …
> [BUGFIX] Fix middleware order for forced indexing

- CHANGELOG.md
- Classes/Command/FlushQueueCommand.php
- Tests/Functional/Command/FlushQueueCommandTest.php
.. the repository has already been flushed already when the message is shown. No need to say it "will be" flushed in the future.
The time form in the flush command status message is wrong:
```
$ ./vendor/bin/typo3cms crawler:flushQueue all
All entries in Crawler queue will be flushed
```
The repository already deleted the data when the message is shown.
This PR changes the message to past tense to indicate this.
**I have**
> [BUGFIX] Change tense in flush command message

- CHANGELOG.md
- Classes/Command/BuildQueueCommand.php
Fix deprecation warnings occurring with PHP >= 8.2
Solves #1011 and #1007 for v11.x branch.
PR for main branch also available #999.
NOTE: I split the CHANGELOG.md change to a separate commit on purpose to allow using the actual changes as patch with `cweagans/composer-patches`.
Feel free to squash the commits when merging the PR!
**I have**
> [TASK] Avoid deprecations in PHP 8.2 (v11.x)

- CHANGELOG.md
- Classes/Middleware/FrontendUserAuthenticator.php
Check if `$queueRec` is in a usable state
Resolves #1031 
**I have**
> [BUGFIX] Check queueRec before usage to avoid PHP errors

- CHANGELOG.md
- Classes/Domain/Repository/QueueRepository.php
- Tests/Functional/Domain/Repository/QueueRepositoryTest.php
- Tests/Functional/Fixtures/tx_crawler_queue.csv
This PR provides a test and fix for #1082 - changes the param-type of `processId` in the prepared statement to `string` instead of `integer`, since the database field already uses `varchar(50)` and `ProcessQueueCommand` will pass a string.
That can lead to either non-matches (sqlite) or even runtime errors (in one of our environments using MariaDB).
**I have**
@tomasnorre I tried my best to get the test to reproduce. For some reason, only the SQLite one ran on my machine. For SQLite, there is no runtime error, but non-numeric values are not matched, leading the test case to fail the count-check which is somewhat sufficient to evaluate the problem.
I'd appreciate if you could check the MySQL and PostgreSQL derivates if they work correctly (either throw and exception or at least fail the …
> Fix: ProcessQueue throws truncated incorrect decimal value

- CHANGELOG.md
- Classes/Service/ConfigurationService.php
> Backport of #1009

- CHANGELOG.md
- Classes/Exception/CrawlerObjectException.php
- Classes/Exception/TimeStampException.php
Deprecates CrawlerObjectException and TimeStampException
**I have**
> Deprecate: CrawlerObjectException and TimeStampException

- .github/workflows/Coveralls.yml
- Classes/CrawlStrategy/SubProcessExecutionStrategy.php
> ci: Update coveralls token in workflow

- .gitignore
- composer.json
> ci: add compser test:coverage to script section

- .github/workflows/BackwardCompatibilityCheck.yml
- CHANGELOG.md
- Classes/Controller/CrawlerController.php
- Documentation/Configuration/PageTsconfigReference(txCrawlercrawlercfg)/Index.rst
This typecasts force_ssl to int PageTS Crawler Configurations.
Resolves #1000 
**I have**
> BUGFIX: Typecast PageTS Crawler Configuration force_ssl to int

- Documentation/Configuration/Examples/News/Index.rst
The pid's in the EXT:news docs code example are incorrect. This PR sets the pid's in the code example as shown in the screenshot.
> [BUGFIX] Use proper pid's in EXT:news docs code example

- CHANGELOG.md
- Classes/Converter/JsonCompatibilityConverter.php
Since PHP 8.3, unserialize() throws an E_WARNING instead of E_NOTICE. This leads to an error when viewing crawler information for pages and when crawling sites:
> PHP Warning: unserialize(): Error at offset 0 of 122 bytes
> in typo3conf/ext/crawler/Classes/Converter/JsonCompatibilityConverter.php line 39
This patch solves the problem in the most non-invasive way by simply catching the unserialize warning.
Resolves: https://github.com/tomasnorre/crawler/issues/1087
**I have**
> [BUGFIX] Catch E_WARNING when unserialize() fails

- CHANGELOG.md
- Classes/Backend/RequestForm/LogRequestForm.php
- phpstan-baseline.neon
In Info > Site Crawler > Crawler log:
As soon as the backend user activated the "Show Result Log" checkbox one time, the columns "Scheduled" and "Run-time" are empty when the checkbox is disabled.
The reason is that the variable's value is not taken into account, only its existence in the user session data.
**I have**
> [BUGFIX] Fix showing "Scheduled" and "Run-time" columns in backend log

- CHANGELOG.md
- Classes/Command/BuildQueueCommand.php
- Classes/Service/ProcessService.php
- Tests/Functional/Service/ProcessServiceTest.php
Resolves #1125, but ensuring that the correct typo3 binary is returned in non-compose installations. 
**I have**
> [BUGFIX] Ensure that correct typo3 binary is returned in non-composer installations

- CHANGELOG.md
- cli/bootstrap.php
Fixes the path issue in `cli/bootstrap.php` as is don't represent the new folder structure in TYPO3. 
**I have**
> [BUGFIX] Adjust path in cli/bootstrap.php to match new folder structure of where extensions are installed

- CHANGELOG.md
- Classes/CrawlStrategy/GuzzleExecutionStrategy.php
Set guzzle connect timeout to 5 seconds.
Default connect timeout behavior is to wait indefinitely, which means that crawler would hang forever in case the server has problems.
https://docs.guzzlephp.org/en/stable/request-options.html#connect-timeout
**I have**
> [BUGFIX] Set guzzle connect timeout to 5 seconds

- CHANGELOG.md
- Classes/CrawlStrategy/SubProcessExecutionStrategy.php
Up to now, the sub process execution strategy did not detect errors. The HTML of error pages was provided as content, and the backend showed an "OK" status.
Since cli/bootstrap.php does not set a non-zero exit code on errors, we have to parse the HTML ourselves to detect if an error occured.
This patch supports TYPO3 error pages and extracts HTTP status code, status message and error message from it.
Error informationare logged into the debug log as well as made visible in the backend site crawler log view.
**I have**
> [FEATURE] Extract error information in SubProcess crawl strategy

- CHANGELOG.md
- Classes/Converter/JsonCompatibilityConverter.php
- Classes/CrawlStrategy/CrawlStrategyInterface.php
- Classes/CrawlStrategy/GuzzleExecutionStrategy.php
- Classes/CrawlStrategy/SubProcessExecutionStrategy.php
- Classes/QueueExecutor.php
- Tests/Unit/Converter/JsonCompatibilityConverterTest.php
- Tests/Unit/CrawlStrategy/GuzzleExecutionStrategyTest.php
- Tests/Unit/Domain/Model/ProcessTest.php
- Tests/Unit/Service/ProcessServiceTest.php
- phpstan-baseline.neon
Let the guzzle crawl strategy return errors in the same way that the subprocess strategy does: As array inside an 'errorlog' array.
Also rework the logic that JsonCompatibilityConverter uses to decide when to `unserialize()`.
And fix some phpunit deprecations, and document the crawl strategy return value structure.
Resolves: https://github.com/tomasnorre/crawler/issues/1166
**I have**
> [BUGFIX] Prevent warning when guzzle crawl requests return errors

- CHANGELOG.md
- Classes/CrawlStrategy/GuzzleExecutionStrategy.php
- Classes/Service/UrlService.php
- Documentation/Troubleshooting/Index.rst
- Tests/Unit/CrawlStrategy/GuzzleExecutionStrategyTest.php
When the web server filters incoming and outgoing HTTP headers, the `X-T3Crawler-Meta` header (needed to transport crawler information back from indexing) may also get filtered away.
This patch lets crawler detect that problem and show it in the backend process log.
**I have**
> [FEATURE] Expose error when crawl response has no X-T3Crawler-Meta header

- Classes/Service/PageService.php
Implicitly marking parameter `$eventDispatcher` as nullable is deprecated. Now the explicit nullable type has been used instead.
> Declare parameter explicitly nullable
